[DC 2021] Launch with dates
devopsdays/devopsdays-web pull request #10240
Opened 2021-04-02 16:11 UTC by nathenharvey

Signed-off-by: Nathen Harvey <nathen.harvey@gmail.com>

2021-04-07 13:42 UTC, robbkidd approved these changes
![Announcing ...](https://user-images.githubusercontent.com/517302/113876246-8c95bc80-9785-11eb-8e87-4e9ccbd6c93a.gif)

2021-04-10 22:28 UTC, MikeRosTX requested changes
Pleas set all 3 CFP date following the same format syntax as start and end dates.

**set all three at once**

2021-04-11 15:21 UTC, robbkidd commented on data/events/2021-washington-dc.yml
> +cfp_date_start:  2021-04-16
```suggestion
cfp_date_start:  2021-04-16T00:00:00-04:00
```

2021-04-11 15:22 UTC, robbkidd commented on data/events/2021-washington-dc.yml
>  cfp_date_announce:  # inform proposers of status
@nathenharvey Do we have the timeline for the rest of the CFP process (closure and accept/decline announcement)?

2021-04-12 12:10 UTC, MikeRosTX approved these changes

2021-04-12 13:49 UTC, MikeRosTX approved these changes
Looks fine by me. 😉 👍

2021-04-12 13:50 UTC, MikeRosTX commented
@nathenharvey feel free to merge if you like, or I can do it for you.

2021-04-12 14:24 UTC, merged