[TLV-2021] First Commit to Get Started
devopsdays/devopsdays-web pull request #10407
Opened 2021-06-21 11:49 UTC by shar1z

2021-06-21 13:59 UTC, phrawzty requested changes
_Also_, please don't add the `hugo` binary (can't comment on binaries). :)

2021-06-21 13:59 UTC, phrawzty commented on LICENSE
> -Copyright [2016-2019] [devopsdays]
Please do not overwrite `/LICENSE`

2021-06-21 13:59 UTC, phrawzty commented on README.md
> -[![Build Status](https://circleci.com/gh/devopsdays/devopsdays-web.svg?branch=main)](https://circleci.com/gh/devopsdays/devopsdays-web) [![Build status](https://ci.appveyor.com/api/projects/status/3l
Please do not overwrite `/README`

2021-06-21 13:59 UTC, phrawzty commented on content/events/2021-tel-aviv/welcome.md
> +</div>
You may wish to comment this out until you've got non-boilerplate content to display. Your call.

2021-06-21 13:59 UTC, phrawzty commented on data/events/2021-tel-aviv.yml
> +    image: "sally-fields.jpg"
Please populate this with the actual humans in the local team.

2021-06-21 13:59 UTC, phrawzty commented on data/events/2021-tel-aviv.yml
> +    level: gold
This has no visual effect but you probably don't want it.

2021-06-23 15:13 UTC, mattstratton commented on data/events/2021-tel-aviv.yml
> +    level: gold
fwiw it's okay to leave this in as a helpful format reference, but as @phrawzty you might want to delete it if that doesn't help you :)

2021-06-23 16:17 UTC, shar1z commented on data/events/2021-tel-aviv.yml
> +    level: gold
Thank you both - I'll make the edits.  I just wanted to have a placeholder, and only after I committed did I see the John & Jane Doe.  Hopefully in the coming days, I'll actually have the final dates.  So maybe I'll hold.  

Really appreciate it.

2021-06-23 16:19 UTC, phrawzty commented on data/events/2021-tel-aviv.yml
> +    level: gold
@shar1z  imho at this point you probably just want to close this PR and open a new one when you're ready.

2021-07-05 20:38 UTC, shar1z reviewed
@mattstratton @phrawzty - Ok - I think I'm ready to announce the event - and I also think I made the relevant edits from the previous commits.

LMK if we're good to merge.

Thanks!

2021-07-05 20:44 UTC, mattstratton commented
Please see @phrawzty's comments on the files to exclude (the hugo binary and LICENSE) and remove them from this PR; as dan mentioned, it might be easier to just start a new PR at this point?

2021-07-05 20:44 UTC, mattstratton commented on LICENSE
> -Copyright [2016-2019] [devopsdays]
@shar1z this commit needs to be removed; you can't change the LICENSE :)

2021-07-05 20:45 UTC, mattstratton commented on README.md
> -[![Build Status](https://circleci.com/gh/devopsdays/devopsdays-web.svg?branch=main)](https://circleci.com/gh/devopsdays/devopsdays-web) [![Build status](https://ci.appveyor.com/api/projects/status/3l
@shar1z this is another file that should not be changed in the PR

2021-07-05 20:46 UTC, mattstratton commented
@shar1z I was able to remove the two files (README and LICENSE) from this PR, but the `hugo` binary I cannot remove from the PR. We cannot merge this when the binary is attached; I would suggest rebasing your fork/branch and submitting a new PR?

2021-07-05 20:49 UTC, mattstratton commented on LICENSE
> -Copyright [2016-2019] [devopsdays]
I took care of this part

2021-07-05 20:50 UTC, mattstratton commented on README.md
> -[![Build Status](https://circleci.com/gh/devopsdays/devopsdays-web.svg?branch=main)](https://circleci.com/gh/devopsdays/devopsdays-web) [![Build status](https://ci.appveyor.com/api/projects/status/3l
I think I resolved this

2021-07-06 11:37 UTC, merged