[MDE-2021] Updating logo of the event and adding sponsors (updating logo for Ceiba)
devopsdays/devopsdays-web pull request #10405
Opened 2021-06-20 02:10 UTC by mpinedag12

[MDE-2021] Updating logo of the event and adding sponsors (updating logo for Ceiba)

2021-06-21 13:40 UTC, phrawzty requested changes

2021-06-21 13:40 UTC, phrawzty commented on data/sponsors/ngix2021.yml
> +name: "ngix2021"
Again, the name of the company is "Nginx", but moreover, the process for changing a logo for a sponsor is documented here: https://github.com/devopsdays/devopsdays-web/blob/main/utilities/README.md#updating-a-sponsor-image-or-data

Please use that method to change the sponsor logo. If you need any help, ping us in #websites on the Slack, or comment here. 👍

2021-06-21 13:40 UTC, phrawzty commented on data/events/2021-medellin.yml
> +  - id: ngix2021
The name of the company in Nginx, not `ngix`.

2021-06-23 10:37 UTC, phrawzty approved these changes

2021-06-23 10:38 UTC, phrawzty requested changes

2021-06-23 10:38 UTC, phrawzty commented on data/events/2021-medellin.yml
> +  - id: nginx
One last thing: please remove `static/img/sponsors/ngix2021.png ` from this PR as it's no longer used. We'll be good to merge after that!

2021-06-25 00:51 UTC, bridgetkromhout commented on data/events/2021-medellin.yml
> +  - id: nginx
I'll remove it

2021-06-25 00:52 UTC, merged