Updating information about 2021-poznan event
devopsdays/devopsdays-web pull request #10497
Opened 2021-08-04 12:35 UTC by luprzybyl

List of changes:
* disabled CFP
* enabled link for tickets
* updated agenda
* updated speaker information

2021-08-12 19:13 UTC, bridgetkromhout commented
Status: someone on the core team needs to review this PR.

2021-08-16 09:25 UTC, luprzybyl commented
Hi Core team, can I ask someone to have a look? This PR blocks us from starting announcing the event. Thanks!

2021-08-16 10:05 UTC, phrawzty requested changes

2021-08-16 10:05 UTC, phrawzty commented on data/events/2021-poznan.yml
>      type: talk
To be clear, this will render as such:
![image](https://user-images.githubusercontent.com/625232/129546099-d9f630e1-2596-4bfd-995e-5c33283645a2.png)

This is because the template connects the contents of `title` to a *program*, not a speaker; in this case, `content/events/2021-poznan/program/manuel-pais.md`. Since that file doesn't exist, you get a `-` here.

This is true of all of your program entries.

2021-08-16 10:05 UTC, phrawzty commented on content/events/2021-poznan/program/bartlomiej-sliwinski.md
> +Speakers = ["manuel-pais"]
The filenames in `/program/` share a relationship with the value of `title:` in your event. You probably want to make a new `manuel-pais.md` file instead.

2021-08-17 20:10 UTC, luprzybyl commented on data/events/2021-poznan.yml
>      type: talk
Thank you for the hint. I have fixed entire agenda.

2021-08-17 20:39 UTC, luprzybyl commented on content/events/2021-poznan/program/bartlomiej-sliwinski.md
> +Speakers = ["manuel-pais"]
I have updated the files. This particular one became obsolete and was removed.

2021-08-18 20:31 UTC, luprzybyl commented
Hi, I have addressed all change requests. @phrawzty , is there anything else we should do before the merge?

2021-08-19 07:44 UTC, phrawzty commented
Hello, thanks for your patience (I was AFK yesterday). LGTM!

2021-08-19 07:44 UTC, merged