[POZ-2021] sponsors and speaker fix
devopsdays/devopsdays-web pull request #10643
Opened 2021-10-04 11:57 UTC by Kacperek0

*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

2021-10-04 14:52 UTC, phrawzty requested changes

2021-10-04 14:52 UTC, phrawzty commented on data/events/2021-poznan.yml
> +    level: bronze
If you take a look at the preview, you'll note that none of these sponsors appear:

![image](https://user-images.githubusercontent.com/625232/135873468-2b5d846c-210b-4d93-9d44-e124a6685f71.png)

That's because the `level`s you're using here are not valid `sponsor_levels` later in this file. You'll need to either add these levels, or use existing ones.

2021-10-05 09:22 UTC, Kacperek0 commented on data/events/2021-poznan.yml
> +    level: bronze
@philcryer Thanks :) fixed!

2021-10-05 10:00 UTC, phrawzty approved these changes

2021-10-05 10:01 UTC, merged