[EHV 2022] Initial bootstrap of the 2022 event
devopsdays/devopsdays-web pull request #10722
Opened 2021-11-20 17:44 UTC by PaulusTM

Initial bootstrap of the Eindhoven event.
Will update with details in the coming weeks.

2021-11-29 12:28 UTC, phrawzty requested changes
Thank you for your patience. Some small items…

2021-11-29 12:28 UTC, phrawzty commented on data/events/2022-eindhoven.yml
> +  - name: location
As you haven't filled out `location.md`, either do that _or_ leave this commented out for now.

```suggestion
  # - name: location
```

2021-11-29 12:28 UTC, phrawzty commented on data/events/2022-eindhoven.yml
> +cfp_date_end: 2021-09-21T00:00:00+02:00 # close your call for proposals.
These dates are in the past. I _think_ you meant 2022…
```suggestion
cfp_date_start: 2022-07-07T00:00:00+02:00 # start accepting talk proposals.
cfp_date_end: 2022-09-21T00:00:00+02:00 # close your call for proposals.
```

2021-11-29 12:28 UTC, phrawzty commented on data/events/2022-eindhoven.yml
> +team_members: # Name is the only required field for team members.
Your `@devopsdays.org` distribution list contains 11 members, but this list contains nine. Please send an email to `info@devopsdays.org` with the names and email addresses of the people on the 2022 team so that we can keep these two lists concurrent.

2021-11-29 21:44 UTC, PaulusTM commented on data/events/2022-eindhoven.yml
> +cfp_date_end: 2021-09-21T00:00:00+02:00 # close your call for proposals.
The CFP has been open since 2021, but you are right.. need to update the close to 2022.

2021-11-29 22:05 UTC, PaulusTM commented on data/events/2022-eindhoven.yml
> +  - name: location
This page is now updated

2021-11-30 22:16 UTC, PaulusTM commented on data/events/2022-eindhoven.yml
> +team_members: # Name is the only required field for team members.
The list is checked, they are in sync now.

2021-11-30 22:19 UTC, PaulusTM commented
@phrawzty All your requests are processed.

2021-12-01 09:36 UTC, phrawzty approved these changes

2021-12-01 09:50 UTC, merged