[MEL-2022] Open 2022 event + add Stile as sponsor
devopsdays/devopsdays-web pull request #10736
Opened 2021-12-07 00:48 UTC by DXPetti

Opening up the Melbourne 2022 event website with the following:

- Call for papers details and link added
- Ticket sales details and link added
- (Re)confirmed Gold sponsors added (including data and logo file for Stile education)
- Direct link to location's COVIDSafe plan added to COVID-19 information banner

2021-12-10 07:56 UTC, yvovandoorn requested changes

2021-12-10 07:56 UTC, yvovandoorn commented on content/events/2022-melbourne/welcome.md
> +    <a href="https://www.papercall.io/devopsdays-melb-2022">Propose a talk!</a>
Since you're setting cfp_link properly in the data file, there is no need to hard code the URL here.

2021-12-10 07:56 UTC, yvovandoorn commented on content/events/2022-melbourne/welcome.md
> +    <a href="https://ti.to/devopsaustralia/melbourne-2022">Register to attend the conference!</a>
Since `registration_link` is set in the data file, there is no need to hard code the URL here.

2021-12-12 04:52 UTC, DXPetti reviewed
Thanks Yvo for the suggestions. Happy to take them onboard

2021-12-12 04:52 UTC, DXPetti commented on content/events/2022-melbourne/welcome.md
> +    <a href="https://ti.to/devopsaustralia/melbourne-2022">Register to attend the conference!</a>
Hey Yvo,

I thought as much myself but in testing with Hugo, that didn't seem to be the case. Instead the link would go to the unused registration page instead of the redirection.

2021-12-12 04:52 UTC, DXPetti commented on content/events/2022-melbourne/welcome.md
> +    <a href="https://www.papercall.io/devopsdays-melb-2022">Propose a talk!</a>
Hey Yvo,

I thought as much myself but in testing with Hugo, that didn't seem to be the case. Instead the link would go to the unused CFP page instead of the redirection.

2021-12-15 11:16 UTC, merged