[KYIV-2022] revive Kyiv 2022 event, online
devopsdays/devopsdays-web pull request #11018
Opened 2022-03-31 18:40 UTC by delgod

2022-03-31 20:17 UTC, mattstratton requested changes
we'll need to figure out a different way around this; changing the stylesheet of the whole theme is not trivial :/

2022-03-31 20:26 UTC, mattstratton commented
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMzM0NTlhMDQtOTM3OS00NzNkLTg1MTctYTI1YTIwOGVmMzZhIiwiZGVwbG95X2lkIjoiNjI0NWY5MmVlZjI2Y2QwMDA4ZTM2NTJhIiwiaWQiOiIwOGUxNjhlZi0zYzQ5LTQ4YzAtOTFhNy1hYjg0ZTdmYmEwYWYifQ==)

This is when `word_break` is unchecked


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 99.0.4844.84 on Mac OS 10.15.7
Viewport:  1673 x 1316 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-11018--devopsdays-web.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=99.0&resolution=1673x1316&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-11018--devopsdays-web.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6245f92eef26cd0008e3652a&commentID=62460e75a31efe183924ad1f&resolution=resolved)

2022-03-31 20:42 UTC, mattstratton requested changes

2022-03-31 20:42 UTC, mattstratton commented on themes/devopsdays-theme/static/scss/custom.scss
> +  word-break: break-word;
please remove the SCSS and CSS changes; they don't actually seem to be working in the deploy preview (see comments in the PR thread)

2022-04-01 05:29 UTC, delgod commented on themes/devopsdays-theme/static/scss/custom.scss
> +  word-break: break-word;
@mattstratton without the change name is terribly wrong on low resolutions, see screen shot below
<img width="797" alt="Screenshot 2022-03-31 at 18 48 13" src="https://user-images.githubusercontent.com/303592/161200625-1a0afbe1-d49b-44e3-8710-8751c78b80dc.png">

2022-04-01 09:20 UTC, antonbabenko commented on content/events/2022-kyiv/welcome.md
> +aliases = ["/events/2022-kiev", "/events/2022-kyiv/", "/events/2022-ukraine/"]
Can we drop `2022-kiev` completely? `2022-kyiv` is much better.

2022-04-01 09:30 UTC, mattstratton commented on themes/devopsdays-theme/static/scss/custom.scss
> +  word-break: break-word;
I see - although the fix seems not to work on larger screens (see my screenshot)

2022-04-01 12:15 UTC, yvovandoorn commented
@mattstratton assigning this one to you so you can merge when its good to go.

2022-04-01 12:21 UTC, mattstratton commented on content/events/2022-kyiv/welcome.md
> +aliases = ["/events/2022-kiev", "/events/2022-kyiv/", "/events/2022-ukraine/"]
there is an impact to how the site will treat grouping the previous events, although we can add the `event_group` parameter to the current and previous events to group them together (example: https://github.com/devopsdays/devopsdays-web/blob/main/data/events/2016-sydney.yml#L4)

I am still slightly confused because I was under the impression that this event was wanted to be under the /events/2022-ukraine path, which is fine either way.

2022-04-01 12:21 UTC, mattstratton commented on themes/devopsdays-theme/static/scss/custom.scss
> +  word-break: break-word;
I don't think either of these is a good overall experience, but the larger screen experience is probably less bad.

I'm okay merging this and once it's live I can see if I can figure out a CSS trick to make it happier.

2022-04-01 12:23 UTC, mattstratton commented on content/events/2022-kyiv/welcome.md
> +aliases = ["/events/2022-kiev", "/events/2022-kyiv/", "/events/2022-ukraine/"]
you need that alias there because there might be links out there that catch it. Those are just all options but not ever displayed in a link, if that makes sense.

2022-04-01 12:24 UTC, mattstratton commented
Overall I am okay with this. We need to update the `/static/_redirects` file (we can include /ukraine as a redirect as well) but that's not blocking, and I'll do that after this gets merged.

2022-04-01 12:24 UTC, mattstratton approved these changes
This is approved, but we will want to look at fixing the display of the name on larger screens on the home page.

2022-04-01 12:25 UTC, merged