[DET-2022] adding 2022 event
devopsdays/devopsdays-web pull request #11102
Opened 2022-04-18 12:54 UTC by rexroof

*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

2022-04-18 20:15 UTC, mattstratton commented
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMzM0NTlhMDQtOTM3OS00NzNkLTg1MTctYTI1YTIwOGVmMzZhIiwiZGVwbG95X2lkIjoiNjI1ZDVmODhjNjgxOGIwMDA5OGQyMmIzIiwiaWQiOiI2ZDNjMjI1ZC1mOTlmLTQ4ZWEtOTFmYS1hMmQ2NTI2ZWExODEifQ==)

The images for your organizers are all broken :)

<details><summary>Browser metadata</summary>





```
Path:      /events/2022-detroit/contact
Browser:   Chrome 100.0.4896.88 on Mac OS 10.15.7
Viewport:  1673 x 1316 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-11102--devopsdays-web.netlify.app%2Fevents%2F2022-detroit%2Fcontact&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=100.0&resolution=1673x1316&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-11102--devopsdays-web.netlify.app/events/2022-detroit/contact) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=625d5f88c6818b00098d22b3&commentID=625dc6fc18f2b8046d6bffd5&resolution=resolved)

2022-04-19 14:05 UTC, mattstratton requested changes

2022-04-19 14:05 UTC, mattstratton commented on data/events/2022-detroit.yml
> +    image: "logo-square.jpg"
I think I see what you're trying to do here, but the image for an organizer goes in the `static/events/YYYY-CITY/organizers/` folder. If you don't want to have images for your organizers, just remove the entire `image` field for each of them! Right now it's just making broken images.

2022-04-23 18:14 UTC, rexroof commented
took me a few days to get back to this, I removed the image: attributes from the organizer entries.

2022-04-23 18:44 UTC, mattstratton approved these changes

2022-04-23 18:45 UTC, merged