(RIO/2022): new event - tbd date
devopsdays/devopsdays-web pull request #11244
Opened 2022-05-19 01:19 UTC by camilla-m

*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

2022-05-19 03:21 UTC, MikeRosTX requested changes
Please email the core team a list of all the new organizers:

**full name - email**

2022-05-20 14:18 UTC, somatorio commented
Slack/List/Website sync done :)

2022-05-20 14:18 UTC, somatorio approved these changes

2022-05-20 14:26 UTC, MikeRosTX approved these changes

2022-05-20 14:27 UTC, merged