[JKT-2022] Initial event commit for DevOpsDays Jakarta 2022
devopsdays/devopsdays-web pull request #11396
Opened 2022-06-22 13:23 UTC by mademulia

[JKT-2022] Initial event commit for DevOpsDays Jakarta 2022, including all details and sponsors.

2022-06-25 13:40 UTC, mademulia commented
Hi @MikeRosTX, 

Can you please help to review the PR? We need to have it up for the DevOpsDays Jakarta
Thank you

2022-06-26 04:26 UTC, MikeRosTX requested changes
This folder needs to be renamed:

**FROM** - /content/events/2022-jakarta/program/
**TO** - /content/events/2022-jakarta/program/

2022-06-26 04:26 UTC, MikeRosTX commented on data/events/2022-jakarta.yml
> +    url: "mailto:devopsdaysjkt@gmail.com"
It is recommended removing this email from the Sponsor navbar so it can be redirected to the Sponsor.md page.
Also, you should not be using your own personal email, you should be using the one created for your team which is **_jakarta@devopsdays.org_**.

Please email the Core team a list of which organizers are **_New for 2022_** and which ones from **_2020 were Removed._**

2022-06-26 04:32 UTC, MikeRosTX commented
> This folder needs to be renamed:
> 
> **FROM** - /content/events/2022-jakarta/program/ **TO** - /content/events/2022-jakarta/program/

Apologies didn't mean to see you needed to rename - /content/events/2022-jakarta/program/.
But you do need to have a - /content/events/2022-jakarta/speakers/ folder.

2022-06-26 06:13 UTC, mademulia commented
Hi @MikeRosTX, Thanks for reviewing, I have updated some files as recommended.

2022-06-26 07:55 UTC, MikeRosTX requested changes
Also, the Speakers navbar is not fixed because it is not listing the speakers. Needs to be fixed.

2022-06-26 07:55 UTC, MikeRosTX commented on data/events/2022-jakarta.yml
> +organizer_email: "devopsdaysjkt@gmail.com" # Put your organizer email address here
You have to use **_jakarta@devopsdays.org_**.

2022-06-26 08:07 UTC, mademulia commented on data/events/2022-jakarta.yml
> +organizer_email: "devopsdaysjkt@gmail.com" # Put your organizer email address here
Hi @MikeRosTX, sure, I just updated the email and speaker navbar as suggested.
Thank you

2022-06-26 17:17 UTC, MikeRosTX requested changes
All the pages look good. 

Once Core receives an email with the **_full name_** and **_email_** of all the organizers for 2022, we will proceed to make sure all 11 organizers are on **_jakarta@devopsdays.org_** and on slack.

2022-06-27 12:11 UTC, mademulia commented
Thanks, I just sent an email to Core Organizer of DevOpsDays for all 11 Organizer's emails

2022-06-28 04:12 UTC, MikeRosTX approved these changes

2022-06-28 04:13 UTC, merged