[WAW-2022] Add Warsaw 2022
devopsdays/devopsdays-web pull request #11432
Opened 2022-06-29 10:56 UTC by MilyMilo

Adding Warsaw 2022: https://devopsdays.pl/
A lot of stuff is still in works, but we wanted to create the initial page already.

2022-06-29 19:49 UTC, MikeRosTX requested changes

2022-06-29 19:49 UTC, MikeRosTX commented on data/events/2022-warsaw.yml
> +    url: "mailto:olga.michaliszyn@proidea.pl"
Please remove the email from the navbar so that Sponsor.md page can be displayed.

2022-06-30 10:07 UTC, MilyMilo commented
@MikeRosTX done 🙌🏻

2022-07-01 04:21 UTC, MikeRosTX approved these changes

2022-07-01 04:21 UTC, merged