Devopsdays lagos2022
devopsdays/devopsdays-web pull request #11554
Opened 2022-07-25 06:35 UTC by haroldsphinx

2022-07-27 09:48 UTC, phrawzty requested changes

2022-07-27 09:48 UTC, phrawzty commented on data/events/2022-lagos.yml
> +cancel: "true"
Your event won't appear on the website it this is set to `true`.

```suggestion
cancel: "false"
```

2022-07-27 09:48 UTC, phrawzty commented on data/events/2022-lagos.yml
> +startdate:  # The start date of your event. Leave blank if you don't have a venue reserved yet.
It's OK if you don't have the exact date yet. I understand that you're thinking of either 29 October or 5 November. What needs to be resolved on your end in order to lock a specific date into place?

2022-07-27 09:48 UTC, phrawzty commented on data/events/2022-lagos.yml
> +team_members: # Name is the only required field for team members.
Note to admins: the DL is up to date.

2022-07-30 15:09 UTC, haroldsphinx commented on data/events/2022-lagos.yml
> +startdate:  # The start date of your event. Leave blank if you don't have a venue reserved yet.
We have finally been able to conclude on this to be October 29th, I have updated it in the code as well

2022-08-01 09:25 UTC, somatorio commented on data/events/2022-lagos.yml
> +cfp_date_start: August 1st, 2022 # start accepting talk proposals.
Both should be in the following format: YYYY-MM-DDTHH:MM:SS+TZ:TZ

Example: 2022-10-29T08:00:00+01:00

2022-08-01 09:26 UTC, somatorio commented on data/events/2022-lagos.yml
> +startdate: October 29th, 2022 # The start date of your event. Leave blank if you don't have a venue reserved yet.
All dates should be in the following format: YYYY-MM-DDTHH:MM:SS+TZ:TZ

Example: 2022-10-29T08:00:00+01:00

2022-08-01 09:51 UTC, somatorio requested changes
There's a lot of files renaming and some *.icloud files that should be looked into, all into other cities, was that some script or something like this?

2022-08-01 09:51 UTC, somatorio commented on data/events/2022-lagos.yml
> +coordinates: "6.54451° N, 3.39226° E" # The coordinates of your city. Get Latitude and Longitude of a Point: http://itouchmap.com/latlong.html
Should be "6.5410064, 3.3970042"

2022-08-01 09:51 UTC, somatorio commented on data/events/2022-lagos.yml
> +organizer_email: "ga" # Put your organizer email address here
Should be lagos@devopsdays.org

2022-08-01 09:51 UTC, somatorio commented on static/_redirects
> +/amsterdam/*		/events/2020-amsterdam/:splat		302
Your PR should not change other devopsdays redirects... I suspect that your fork is outdated, maybe you need to run `git pull upstream main --rebase`? ([Provided you set the upstream origin](https://github.com/devopsdays/devopsdays-web/blob/main/CONTRIBUTING.md#setting-your-fork-up-the-first-time))

2022-08-01 09:51 UTC, somatorio commented on static/_redirects 2
> +/amsterdam/*		/events/2022-amsterdam/:splat		302
I don't think this files should be here...?

2022-08-01 11:56 UTC, closed without merging