DevOpsDays Lagos
devopsdays/devopsdays-web pull request #11597
Opened 2022-08-01 11:57 UTC by haroldsphinx

- CFP page updated

2022-08-01 12:31 UTC, phrawzty requested changes

2022-08-01 12:31 UTC, phrawzty commented on data/events/2022-lagos.yml
> +registration_date_end: October 28th, 2022 # close registration. Leave blank if registration is not open yet.
All dates must be in the format `YYYY-MM-DDTHH:MM:SS+TZ:TZ`, as is indicated in this exact file (see lines 9—11). This was feedback on your other PR (that you closed) also.

2022-08-01 12:31 UTC, phrawzty commented on data/events/2022-lagos.yml
> +organizer_email: "ga" # Put your organizer email address here
Not sure what `ga` is but this must be your mailing list.

```suggestion
organizer_email: "lagos@devopsdays.org" # Put your organizer email address here
```

2022-08-01 12:31 UTC, phrawzty commented on data/events/2022-lagos.yml
> +cfp_link: "https://sessionize.com/localhost-conference-2022" #if you have a custom link for submitting proposals, add it here. This will control the Propose menu item as well as the "Propose" button.
The branding here makes it quite clear that this is an event called "Localhost".

![image](https://user-images.githubusercontent.com/625232/182147907-ab2e8772-617f-4ea1-8d58-640903e20ecf.png)

DevOpsDays—the global brand—is _not_ "presenting" this event. If you intend to co-locate `DevOpsDays Lagos` alongside the Localhost event, that's fine, but you need to be extremely clear with the branding.

2022-08-01 12:31 UTC, phrawzty commented on data/events/2022-lagos.yml
> +  - name: sponsor
Keep this disabled until you're ready to accept sponsors (see also line 78).

```suggestion
 # - name: sponsor
```

2022-08-01 12:40 UTC, haroldsphinx commented on data/events/2022-lagos.yml
> +cfp_link: "https://sessionize.com/localhost-conference-2022" #if you have a custom link for submitting proposals, add it here. This will control the Propose menu item as well as the "Propose" button.
Yes, working on updating the branding for this

2022-08-01 12:42 UTC, haroldsphinx commented on data/events/2022-lagos.yml
> +  - name: sponsor
We are actually ready to accept sponsorships, updated L78

2022-08-01 13:38 UTC, somatorio commented on data/events/2022-lagos.yml
> +coordinates: "6.54451°, 3.39226°" # The coordinates of your city. Get Latitude and Longitude of a Point: http://itouchmap.com/latlong.html
You need to remove the "°", google maps (on location page) won't be able to pinpoint the location as is

2022-08-01 15:11 UTC, phrawzty commented on data/events/2022-lagos.yml
> +startdate: "2022-10-29T10:00:0+01:00" # The start date of your event. Leave blank if you don't have a venue reserved yet.
The formatting here is really picky.

```suggestion
startdate: "2022-10-29T10:00:00+01:00" # The start date of your event. Leave blank if you don't have a venue reserved yet.
```

2022-08-01 15:11 UTC, phrawzty commented on data/events/2022-lagos.yml
> +coordinates: "6.54451°, 3.39226°" # The coordinates of your city. Get Latitude and Longitude of a Point: http://itouchmap.com/latlong.html
```suggestion
coordinates: "6.54451, 3.39226" # The coordinates of your city. Get Latitude and Longitude of a Point: http://itouchmap.com/latlong.html
```

2022-08-01 15:12 UTC, phrawzty requested changes
More changes requested.

2022-08-04 09:13 UTC, haroldsphinx commented on data/events/2022-lagos.yml
> +cfp_link: "https://sessionize.com/localhost-conference-2022" #if you have a custom link for submitting proposals, add it here. This will control the Propose menu item as well as the "Propose" button.
This has been resolved now

2022-08-04 09:46 UTC, somatorio approved these changes
LGTM, but I want to know @phrawzty opinion on the branding part fix

2022-08-04 12:25 UTC, phrawzty commented
@haroldsphinx,

With all due respect, this is very clearly advertising an event called "Localhost Conference 2022", as proposed by an organisation of the same name. There's nothing here that indicates that it's a DevOpsDays event except some light branding on the ticket sales page.

At this point I am disinclined to accept this PR or sign off on the local chapter.

If you wish to continue, I encourage you and your local team to (re-)read the [organising page](https://devopsdays.org/organizing), and to decide if you're actually running a DevOpsDays event or not. From there, I invite you to send an email to `info@devopsdays.org` with the following details:
- The exact material relationship between Localhost and the proposed DevOpsDays Lagos event
- Proposed / planned schedule for both events
- Strategy for running the mandatory open spaces

To be clear, I am _not_ discouraging you from organising and running a local event. Our responsibility as Core Organisers is to protect the brand, shepherd local events, and curate a fundamental experience. Our goal, therefore, is to help you do just that, if you so choose.

Please take the time to consider this all carefully before acting. If you choose not to associate with the DevOpsDays brand, that's OK—no hard feelings, and I wish you the best for your future events.

If you do want to run a DevOpsDays event, then we'll be happy to engage with you to ensure that it's done correctly. My final piece of advice should you wish to go down this path: I strongly encourage you to consider running a _single, independant DevOpsDays event—unrelated to Localhost_—at least for the first time…

2022-09-05 07:04 UTC, phrawzty commented
This PR has been open for a month with no activity. Let's give it a few more days, and if there's no activity, we'll go ahead and close it.

2022-09-09 08:03 UTC, phrawzty commented
Closing this PR due to inactivity.

2022-09-09 08:03 UTC, closed without merging