[BELEM-2022] Add DevOpsDays Belém 2022 page
devopsdays/devopsdays-web pull request #11854
Opened 2022-09-15 19:37 UTC by pigor

Add the DevOpsDays Belem 2022 event.

2022-09-21 09:53 UTC, phrawzty requested changes

2022-09-21 09:53 UTC, phrawzty commented on content/events/2022-belem/programa.md
> +### <b>Palestre (CFP)</b>
```suggestion
<h3>Palestre (CFP)</h3>
```

Not sure why but the `###` didn't get interpreted as a header. Anyway, try `<h3>` (or whatever level you like) instead.

<img width="407" alt="image" src="https://user-images.githubusercontent.com/625232/191472909-5fbac59d-802d-489e-85de-7ed2de89f11a.png">

2022-09-21 09:53 UTC, phrawzty commented on data/events/2022-belem.yml
> +team_members: # Name is the only required field for team members.
Do you have a third organiser lined up?

2022-09-27 00:34 UTC, pigor commented on content/events/2022-belem/programa.md
> +### <b>Palestre (CFP)</b>
Thanks for feedback, we removed this page, because we add menu link to redirect to papercall.io event page.

2022-09-27 00:35 UTC, pigor commented on data/events/2022-belem.yml
> +team_members: # Name is the only required field for team members.
My bad, I added the other organizers, thanks!

2022-09-27 01:01 UTC, pigor commented
@phrawzty adjusts done.

2022-09-28 13:34 UTC, phrawzty commented on data/events/2022-belem.yml
> +team_members: # Name is the only required field for team members.
You've got six (6) organisers listed here, but only five (5) in the `belem@devopsdays.org` mailing list.

Please send an email to `info@devopsdays.org` with the full definitive list of your local team, including names and email addresses, so that we can ensure it is aligned with the contents of this file.

2022-10-03 14:48 UTC, pigor commented on data/events/2022-belem.yml
> +team_members: # Name is the only required field for team members.
@phrawzty we sent email to update the local team and we update the contato page with definitive list too.

2022-10-07 13:42 UTC, pigor commented on data/events/2022-belem.yml
> +team_members: # Name is the only required field for team members.
@phrawzty do we have any pending to approval this PR?

2022-10-11 20:06 UTC, pigor commented
@phrawzty we sent the updates 8 days ago. Do we have any pending to approval this PR?

2022-10-12 11:11 UTC, phrawzty commented on data/events/2022-belem.yml
> +    url: /events/2022-belem/programa
You don't have a programa page yet, so the link does this:

<img width="661" alt="image" src="https://user-images.githubusercontent.com/625232/195327770-d30eafc6-6dea-4da4-9226-059dadb0d2d2.png">

```suggestion
  # - name: Programa
  #   url: /events/2022-belem/programa
```

2022-10-12 11:12 UTC, phrawzty commented
> we sent the updates 8 days ago. Do we have any pending to approval this PR?

My apologies! This githib notification thread ended up in my spam folder for some reason. :( Anyway, you have a broken link on your page (see comment above) but I'm going to merge this PR anyway. That said, please open another PR to fix that broken link asap.

2022-10-12 11:12 UTC, merged