Advertise the use of Docker for running Hugo
devopsdays/devopsdays-web pull request #11866
Opened 2022-09-18 18:52 UTC by ghoneycutt

2022-09-18 18:54 UTC, ghoneycutt commented
The docs still shared the old way of installing hugo locally, though the recommended way has long been to use `hugoserver.sh` and run through docker. Without this update, people are liable to waste a lot of time getting hugo going as the docker approach is not documented.

2022-09-19 14:35 UTC, bridgetkromhout commented
If I recall correctly, there were recent discussions about questions someone had about the docker approach. Since I haven't tested it with docker, I'll let someone who has tested it vet this update to the docs; thanks.

2022-09-19 16:53 UTC, mattstratton commented
I don't know that I agree with this statement:

> though the recommended way has long been to use hugoserver.sh and run through docker.

The mode we are moving towards as the "recommended" way will be gitpod, which isn't fully documented but works the best actually.

2022-09-19 16:54 UTC, mattstratton requested changes

2022-09-19 16:54 UTC, mattstratton commented on CONTRIBUTING.md
> +#### Run Hugo with Docker (Recommended)
I am not comfortable saying this is "recommended" as it's "unofficially" maintained by us. I do agree with including it like this, and I'm fine making it the "first" choice - I just don't want the word "recommended" on it :)

2022-09-19 16:54 UTC, mattstratton commented on CONTRIBUTING.md
> +# Run through Docker (recommended)
same as the previous comment - keep this, but remove "recommended"

2022-09-21 16:11 UTC, ghoneycutt commented on CONTRIBUTING.md
> +# Run through Docker (recommended)
You have recommended that I use it when I had issues with brew :>

2022-12-13 19:57 UTC, merged