[RIO/2022] new organizer
devopsdays/devopsdays-web pull request #11884
Opened 2022-09-22 01:53 UTC by camilla-m

*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

2022-09-22 23:09 UTC, MikeRosTX requested changes
Please send an email to the core team giving us "**_Willian dos Santos_**" email so we can add him to Rio's team email dl and to Slack.

2022-09-23 14:13 UTC, camistoryblok commented
> Please send an email to the core team giving us "**_Willian dos Santos_**" email so we can add him to Rio's team email dl and to Slack.

But we already did that few days ago and someone said to open the PR first.
Email sent September 15th. @MikeRosTX

2022-09-23 14:20 UTC, MikeRosTX approved these changes

2022-09-23 14:21 UTC, MikeRosTX commented
Found it. My apologies, it got caught up in my SPAM folder.

2022-09-23 14:21 UTC, merged