[ALMATY-2022] Add Almaty event to the website
devopsdays/devopsdays-web pull request #11886
Opened 2022-09-22 11:53 UTC by tabu-a

2022-09-22 12:55 UTC, phrawzty requested changes
p.s. I love the logo! Please send me a t-shirt. ;)

2022-09-22 15:09 UTC, tabu-a commented on data/events/2022-almaty.yml
> +  - id: PS
fixed - thanks!

2022-09-22 15:09 UTC, tabu-a commented on data/events/2022-almaty.yml
> +cfp_date_end:  2022-10-15T09:00:00+06:00 # close your call for proposals.
I've added a link to a form for speakers on our landing page. Thanks!

2022-09-22 15:16 UTC, tabu-a commented
hey @phrawzty - thanks for comments. could you please dm me your shipping address and your t-shirt size on slack? 🙂

2022-09-23 08:36 UTC, phrawzty approved these changes
The Netlify preview isn't regenerating but I think this PR is safe. :)

2022-09-23 08:37 UTC, merged