[FLN-2023]Add Florianópolis 2023 event
devopsdays/devopsdays-web pull request #12143
Opened 2023-01-15 01:23 UTC by lborguetti

This PR add the initial Florianópolis 2023 event content.

Work done in this PR:

* Add event page with the date of the event and organizers;
* Add the welcome page;
* Add the conduct page;
* Add static files [logo, header and organizer pictures];

Note: other files in this PR are boilerplates to future work.

2023-01-16 15:59 UTC, gomex requested changes

2023-01-16 15:59 UTC, gomex commented on data/events/2023-florianopolis.yml
> +enddate:  2023-11-11T19:30:00+03:00
A data só pode ser informaca quando o local do evento for informado. Vocês já tem local?

2023-01-16 23:11 UTC, gomex requested changes

2023-01-16 23:11 UTC, gomex commented on data/events/2023-florianopolis.yml
> +enddate:  2023-11-11T19:30:00+03:00
```suggestion
startdate: # The start date of your event. Leave blank if you don't have a venue reserved yet.
enddate:  # The end date date of your event. Leave blank if you don't have a venue reserved yet.
```

2023-01-19 15:02 UTC, lborguetti commented on data/events/2023-florianopolis.yml
> +enddate:  2023-11-11T19:30:00+03:00
A data foi removida! Obrigado pela informação.

2023-01-19 22:05 UTC, merged