[KRAKOW-2023] Add 2023 edition
devopsdays/devopsdays-web pull request #12197
Opened 2023-01-29 18:58 UTC by MilyMilo

Adding Kraków 2023

2023-01-30 10:55 UTC, phrawzty requested changes

2023-01-30 10:55 UTC, phrawzty commented on data/events/2023-krakow.yml
> +cfp_link: "https://dodkrakow.pl/cfp2023/"
This leads to a 404. Please comment out until the CFP mechanism is ready.

![image](https://user-images.githubusercontent.com/625232/215457370-24741947-5127-4921-ae16-6ac19687481a.png)

2023-01-30 10:55 UTC, phrawzty commented on data/events/2023-krakow.yml
> +    url: "https://eventory.cc/event/devopsdays-krakow-2023"
This page feels like it's not ready, but I'm not familiar with the interface. Is this expected behaviour?

![image](https://user-images.githubusercontent.com/625232/215457576-88cc8c59-f894-40e2-85cb-70a0296e0966.png)

2023-01-30 10:55 UTC, phrawzty commented on data/events/2023-krakow.yml
> +registration_date_end:
Please fill these fields in with the start and end dates of when people can register.

2023-01-30 10:55 UTC, phrawzty commented on data/events/2023-krakow.yml
> +    url: "https://dodkrakow.pl/cfp2023/"
Same comment as [line 24](https://github.com/devopsdays/devopsdays-web/pull/12197/files#diff-17746e68896aef08ac7831d71531a7ecfeb5d373bc242097c9ce6093434055caR24).

2023-02-13 14:00 UTC, phrawzty commented
Hello,

This has been open for a long time without any response. Nobody responded to my query in the `#krakow` channel on Slack either.

I will close this PR for now. Feel free to re-open when you're ready.

2023-02-13 14:00 UTC, closed without merging

2023-02-28 18:47 UTC, ivellios commented
@phrawzty - I have addressed these issues in a separate PR: #12333