[ZRH-2023] added speakers & program (not shown in nav yet - team review pending)
devopsdays/devopsdays-web pull request #12322
Opened 2023-02-26 13:21 UTC by tweinmann

…w in the team)

*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

2023-02-27 20:57 UTC, mattstratton commented
@tweinmann I'm going to mark this PR as "draft", when it's ready for us to review and merge, please move it out of draft status. thanks!

2023-02-27 22:17 UTC, tweinmann commented
> @tweinmann I'm going to mark this PR as "draft", when it's ready for us to review and merge, please move it out of draft status. thanks!

@mattstratton done. thank you!

2023-03-01 05:51 UTC, MikeRosTX requested changes
After a random spot check, found several Speaker pic files over the max **_recommended to be 600px square_**.

Please resize all Speaker pics to comply with recommended reference.

Please reference: [https://github.com/devopsdays/devopsdays-web/blob/main/themes/devopsdays-theme/reference.md#speaker-page-fields](https://github.com/devopsdays/devopsdays-web/blob/main/themes/devopsdays-theme/reference.md#speaker-page-fields)

2023-03-01 06:51 UTC, MikeRosTX approved these changes

2023-03-01 18:51 UTC, merged