[SEA-2023] venue updates and enable sponsorship
devopsdays/devopsdays-web pull request #12588
Opened 2023-04-16 19:17 UTC by harbinger55

2023-04-17 02:28 UTC, MikeRosTX requested changes

2023-04-17 02:28 UTC, MikeRosTX commented on static/events/2023-seattle/Prospectus-2023.pdf
RENAME to all lower case

*FROM*  **_static/events/2023-seattle/Prospectus-2023.pdf_** 

*TO*  **_static/events/2023-seattle/prospectus-2023.pdf_**

Then re-upload the PDF.

2023-04-17 16:26 UTC, mattstratton requested changes

2023-04-17 16:26 UTC, mattstratton commented on static/events/2023-seattle/Prospectus-2023.pdf
actually please remove this file from this PR and instead upload it (and then link to it) in the devopsdays/devopsdays-assets repo (we try to avoid having larger files in this repo)

2023-04-19 00:28 UTC, harbinger55 commented
Sorry for the delay. I have moved the prospectus to devopsdays-assets in PR https://github.com/devopsdays/devopsdays-assets/pull/153 and updated the pages appropriately.

2023-04-19 00:42 UTC, MikeRosTX approved these changes

2023-04-19 00:45 UTC, merged