[Oslo-2023] Add new event
devopsdays/devopsdays-web pull request #12604
Opened 2023-04-19 08:39 UTC by larstobi

Added Oslo 2023 event!

2023-04-19 21:35 UTC, MikeRosTX requested changes
Make changes requested to **_2023-oslo.yml_**.
Oslo email dl and slack have been updated.

2023-04-19 21:35 UTC, MikeRosTX commented on data/events/2023-oslo.yml
> +
**_startdate_** & **_enddate_** need to be removed until you have a confirmed signed contract for a **_location_**.

2023-04-19 21:35 UTC, MikeRosTX commented on data/events/2023-oslo.yml
> +# These are the same people you have on the mailing list and Slack channel.
Images for organisers from 2022 seem to be missing for 2023.

2023-04-21 06:57 UTC, larstobi commented on data/events/2023-oslo.yml
> +
We already have a signed contract for a location with Sentralen, Oslo.

2023-04-21 07:12 UTC, larstobi commented on data/events/2023-oslo.yml
> +# These are the same people you have on the mailing list and Slack channel.
I have now added the organizer images, except for two new organizers who haven't provided images yet.

2023-04-21 12:08 UTC, larstobi commented on data/events/2023-oslo.yml
> +# These are the same people you have on the mailing list and Slack channel.
I have now added the pictures for the two new organizers too.

2023-04-21 13:33 UTC, merged