[INDY-2023] Add prospectus
devopsdays/devopsdays-web pull request #12639
Opened 2023-04-26 15:54 UTC by ghoneycutt

2023-04-26 16:09 UTC, apoland approved these changes

2023-04-26 21:35 UTC, jyee requested changes

2023-04-26 21:35 UTC, jyee commented on static/events/2023-indianapolis/devopsdays-indianapolis-2023-prospectus.pdf
Static files like this shouldn't be added to the main repo. Can you move this to https://github.com/devopsdays/devopsdays-assets?

2023-04-27 01:42 UTC, ghoneycutt commented
Could someone please merge https://github.com/devopsdays/devopsdays-assets/pull/154 first so I can verify this works with netlify.

2023-04-27 02:24 UTC, ghoneycutt commented
Prospectus moved to assets. This is good to go.

2023-04-27 03:10 UTC, merged