[DC-2023] feat: added CFP info for DC-2023
devopsdays/devopsdays-web pull request #12651
Opened 2023-04-30 14:14 UTC by davezen1

- Added CFP links to sessionize for DevOpsDays DC 2023

2023-04-30 14:15 UTC, davezen1 commented
@gallimorej can you take a look?

2023-05-01 06:01 UTC, MikeRosTX requested changes
Let us know once the changes have been made and the PR is ready to be merged.

2023-05-01 06:01 UTC, MikeRosTX commented on data/events/2023-washington-dc.yml
>  # cfp_date_end:  2023-07-11T00:00:00-04:00 # close your call for proposals.
The 3 lines 17, 18, an 19 need to be enabled so that DC CFP appears on this list https://devopsdays.org/speaking

2023-05-01 12:18 UTC, gallimorej commented on data/events/2023-washington-dc.yml
>  # cfp_date_end:  2023-07-11T00:00:00-04:00 # close your call for proposals.
@davezen1 lines 17-19 ought to be:

cfp_date_start: 2023-05-01T00:00:00-04:00 # start accepting talk proposals.
cfp_date_end:  2023-06-26T00:00:00-04:00 # close your call for proposals.
cfp_date_announce:  2023-07-24T00:00:00-04:00 # inform proposers of status

2023-05-01 14:03 UTC, MikeRosTX approved these changes

2023-05-01 14:16 UTC, merged