[TPE-2023] add devopsdays 2023 Taipei event
devopsdays/devopsdays-web pull request #12788
Opened 2023-05-26 07:54 UTC by thebrecht

add devopsdays 2023 Taipei event

2023-05-29 12:47 UTC, phrawzty requested changes

2023-05-29 12:47 UTC, phrawzty commented on data/events/2023-taipei.yml
> + # - name: propose
```suggestion
  - name: propose
```
If the CFP really is open (as `cfp_date_start` and `cfp_open` would suggest), then you need to uncomment this—at a minimum—so that people are directed to your CFP page.

2023-05-29 12:47 UTC, phrawzty commented on data/events/2023-taipei.yml
> +team_members: # Name is the only required field for team members.
There are five (5) entries in this list, but seven (7) in the `taipei@devopsdays.org` mailing list. These lists need to be identical. Please send an email to `info@devopsdays.org` with a definitive list of the five email addresses for the people in `team_members` here.

2023-05-29 12:47 UTC, phrawzty commented on data/events/2023-taipei.yml
> +sponsors_accepted : "No" # Whether you want "Become a XXX Sponsor!" link
No sponsors?

2023-05-29 12:49 UTC, phrawzty commented
Hello @thebrecht,

Alongside the small items noted in the review, I'd like to get some clarification on this part of your CFP page:
![image](https://github.com/devopsdays/devopsdays-web/assets/625232/f586833a-22d0-4f7f-9579-d60ed201f4a9)
Unfortunately I cannot read this but Google Translate suggests that this is some sort of fee or remuneration schedule? Please elaborate. Thank you!

2023-06-02 00:54 UTC, thebrecht commented on data/events/2023-taipei.yml
> + # - name: propose
ok, I will uncomment this.

2023-06-02 01:10 UTC, thebrecht commented on data/events/2023-taipei.yml
> +team_members: # Name is the only required field for team members.
The update email has been sent. Thank you.

2023-06-02 01:25 UTC, thebrecht commented on data/events/2023-taipei.yml
> +sponsors_accepted : "No" # Whether you want "Become a XXX Sponsor!" link
It will change to "Yes".

2023-06-02 03:19 UTC, thebrecht commented
> 



> Hello @thebrecht,
> 
> Alongside the small items noted in the review, I'd like to get some clarification on this part of your CFP page: ![image](https://user-images.githubusercontent.com/625232/241734661-f586833a-22d0-4f7f-9579-d60ed201f4a9.png) Unfortunately I cannot read this but Google Translate suggests that this is some sort of fee or remuneration schedule? Please elaborate. Thank you!

The table you are referring to is the speaker fee schedule. The table indicates the fees for different speaking durations, which are 25 minutes for 3000 NTD(approximately $106 USD), 40 minutes for 5000 NTD (approximately $177 USD), and workshops for 9000 NTD (approximately $318 USD).

2023-06-02 03:28 UTC, thebrecht commented
@phrawzty

Thanks for reviewing my pull request. Should I create a new pull request with the suggested changes, or would you prefer to make the adjustments directly and merge them? Your guidance would be appreciated.

2023-06-02 03:39 UTC, glasnt commented
@thebrecht please update this pull request with the requested changes. Thanks!

2023-06-05 09:14 UTC, phrawzty approved these changes

2023-06-05 09:14 UTC, merged