[FLN-2023] Add date of event
devopsdays/devopsdays-web pull request #12835
Opened 2023-06-06 16:24 UTC by LanusseMorais

*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

2023-06-08 22:02 UTC, MikeRosTX requested changes
We cannot merge this PR until a location address on line 34.

2023-06-09 22:30 UTC, LanusseMorais commented
> We cannot merge this PR until a location address on line 34.

Fixed in new commits

2023-06-09 22:30 UTC, LanusseMorais commented
> We cannot merge this PR until a location address on line 34.

Fixed in new commits

2023-06-10 04:50 UTC, MikeRosTX approved these changes

2023-06-10 05:21 UTC, merged