[PHL-2023] Initial Event Creation
devopsdays/devopsdays-web pull request #12936
Opened 2023-06-28 15:10 UTC by dgrizzanti

*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

2023-06-28 20:05 UTC, MikeRosTX requested changes
Since it is your 1st year back after the pandemic and there are some discrepancies in the list of organizers, please send an email to: info@devopsdays.org

Include full names and email addresses for organizers:
- Returning organizers
- New organizers
- and organizers that should be removed

2023-06-29 03:20 UTC, MikeRosTX commented
Thanks for list Peter! But something doesn't match, because you say Hannah is Exiting but she is listed as an organizer in the PR.  Please confirm.

2023-06-29 10:25 UTC, dgrizzanti commented
@MikeRosTX I’ve removed Hannah from the list

2023-06-29 15:26 UTC, MikeRosTX approved these changes

2023-06-29 15:26 UTC, merged