[LA-2024] Initial commit for Los Angeles 2024
devopsdays/devopsdays-web pull request #13046
Opened 2023-07-22 20:14 UTC by omargohan

**Summary of changes**:

- Initial commit for Los Angeles 2024

**Tested**:

- Locally using Hugo

2023-07-24 09:34 UTC, phrawzty requested changes

2023-07-24 09:34 UTC, phrawzty commented on content/events/2024-los-angeles/about.md
> +We are proud to announce the 13th Annual DevOpsDaysLA will be held Friday, March 15th, 2024. DevOpsDaysLA is an anual event held in Southern California. The conference is volunteer-organized and dedi
```suggestion
We are proud to announce the 13th Annual DevOpsDaysLA will be held Friday, March 15th, 2024. DevOpsDaysLA is an anual event held in Southern California. The conference is volunteer-organized and dedicated to the DevOps community. DevOpsDaysLA is presented in cooperation with the Southern California Linux Expo (SCALE).
```

2023-07-24 09:34 UTC, phrawzty commented on content/events/2024-los-angeles/about.md
> +"DevOps is a set of practices that combines software development (Dev) and IT operations (Ops). It aims to shorten the systems development life cycle and provide continuous delivery with high softwar
Did you mean to make this a link, or is it a footnote?

2023-07-24 09:34 UTC, phrawzty commented on content/events/2024-los-angeles/sponsor.md
> +- 8 Speakers ( 5 Long Form Talks, 3 Lightning Talks)
```suggestion
- 8 Speakers (5 Long Form Talks, 3 Lightning Talks)
```

2023-07-24 09:34 UTC, phrawzty commented on data/events/2024-los-angeles.yml
> +team_members: # Name is the only required field for team members.
Hello,

The `los-angeles@devopsdays.org` mailing list contains seven email addresses, but this list only has six items. Please send an email to `info@devopsdays.org` with the complete list of both names and email addresses so that we can ensure these two things line up.

2023-07-24 19:41 UTC, omargohan commented on content/events/2024-los-angeles/about.md
> +"DevOps is a set of practices that combines software development (Dev) and IT operations (Ops). It aims to shorten the systems development life cycle and provide continuous delivery with high softwar
Footnote

2023-07-24 19:46 UTC, omargohan commented on data/events/2024-los-angeles.yml
> +team_members: # Name is the only required field for team members.
Thank you for the feedback. We will do that once we discuss who else is going to participate this time (beside the list that we have there).

2023-07-25 13:55 UTC, phrawzty commented on data/events/2024-los-angeles.yml
> +team_members: # Name is the only required field for team members.
If you don't have the final list right now, that's OK. Just adjust this for the (minimum) three people in your group and send the email with that list in it.

2023-07-25 20:43 UTC, omargohan commented on data/events/2024-los-angeles.yml
> +team_members: # Name is the only required field for team members.
@phrawzty , can you please let us continue and put the site up? We will provide the list as soon as we have it, but for now we really need the site available to start promoting the event. Thank you for your comprehension.

2023-07-26 09:06 UTC, phrawzty commented on data/events/2024-los-angeles.yml
> +team_members: # Name is the only required field for team members.
@omargohan Fair enough.

2023-07-26 09:06 UTC, phrawzty approved these changes

2023-07-26 09:07 UTC, merged