[PHL-2023] Add 2023 PHL prospectus
devopsdays/devopsdays-web pull request #13093
Opened 2023-08-04 16:38 UTC by dgrizzanti

2023-08-04 17:30 UTC, MikeRosTX requested changes

2023-08-04 17:30 UTC, MikeRosTX commented on static/events/2023-philadelphia/dod-philly-sponsor-prospectus.pdf
Static files like prospectus shouldn't be added to the main repo. 
Can you move this to https://github.com/devopsdays/devopsdays-assets?

2023-08-04 17:31 UTC, mattstratton commented on static/events/2023-philadelphia/dod-philly-sponsor-prospectus.pdf
for reference here is some more details:

 you can host your PDFs for prospectus, etc, in the repo at [devopsdays/devopsdays-assets](https://github.com/devopsdays/devopsdays-assets) and then link to them from there. Files in that repo are presented under their relative URL at https://assets.devopsdays.org/. For example, the file located at static/events/2016/chicago/devopsdays-chicago-2016-prospectus.pdf in the devopsdays/devopsdays-assets repo will be presented at https://assets.devopsdays.org/events/2016/chicago/devopsdays-chicago-2016-prospectus.pdf

2023-08-05 21:36 UTC, dgrizzanti commented on static/events/2023-philadelphia/dod-philly-sponsor-prospectus.pdf
Opened a [PR](https://github.com/devopsdays/devopsdays-assets/pull/168) to the assets repo and updated this PR with the link. Removed PDF. Thanks!

2023-08-05 23:51 UTC, MikeRosTX approved these changes

2023-08-05 23:51 UTC, merged