[KC-2024] create placeholder for 2024 event
devopsdays/devopsdays-web pull request #13131
Opened 2023-08-14 00:59 UTC by jerdog

Put in placeholder for Devopsdays Kansas City 2024 event

2023-08-14 04:14 UTC, MikeRosTX requested changes
Once we 3rd organizer, we can proceed to add #kansas-city to the TBD list.

https://devopsdays.org/organizing#assembling-a-team

You’re going to **_need at least three people_** from three different organizations on your local organizing team, so you have a broader base of support and involvement from the community.

2023-08-14 07:34 UTC, jerdog commented
Yeah that's no problem. We are sorting that now, and will update soon.

On Sun, Aug 13, 2023, 23:14 Mike Rosado ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Once we 3rd organizer, we can proceed to add #kansas-city to the TBD list.
>
> https://devopsdays.org/organizing#assembling-a-team
>
> You’re going to *need at least three people* from three different
> organizations on your local organizing team, so you have a broader base of
> support and involvement from the community.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/devopsdays/devopsdays-web/pull/13131#pullrequestreview-1576042742>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACIPIE62KBPDW3M3F54LDDXVGQ2FANCNFSM6AAAAAA3PADGTM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-06 16:06 UTC, jerdog commented
@MikeRosTX we've got our organizers, I've rebased to main, and we're ready for a merge! 🙌🏻

2023-09-06 20:01 UTC, MikeRosTX approved these changes

2023-09-06 20:01 UTC, merged