[LA-2024] Formatting pages and more
devopsdays/devopsdays-web pull request #13191
Opened 2023-08-25 09:59 UTC by omargohan

**Summary of changes:**

- Applied justified text to all pages.
- Updated sponsor information/page
- Updated contact page

**Tested:**

- Locally using hugo

2023-08-28 09:47 UTC, adrianmoisey commented on data/events/2024-los-angeles.yml
> -    linkedin: "https://www.linkedin.com/in/cmeza99"
When removing an organiser, please email info@devopsdays.org to that we can keep the mailing list and slack up to date

2023-08-28 14:36 UTC, omargohan commented on data/events/2024-los-angeles.yml
> -    linkedin: "https://www.linkedin.com/in/cmeza99"
@adrianmoisey, I have sent an email to info@devopsdays.org

Please let me know if you need anything else.

Thank you!

2023-08-28 15:30 UTC, MikeRosTX requested changes
Cannot merge #13191 until we get **Murriel Perez-McCabe**'s email.

2023-08-28 20:19 UTC, omargohan commented
Email has been sent. Thank you!

2023-08-29 03:46 UTC, MikeRosTX approved these changes

2023-08-29 03:47 UTC, merged