[IST-2024] Initial Istanbul page
devopsdays/devopsdays-web pull request #13291
Opened 2023-09-12 11:35 UTC by developer-guy

*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

2023-09-14 12:57 UTC, phrawzty requested changes

2023-09-14 12:57 UTC, phrawzty commented on data/events/2024-istanbul.yml
> +cfp_link: "https://papercall.io/devopsdays-istanbul-2023" #if you have a custom link for submitting proposals, add it here. This will control the Propose menu item as well as the "Propose" button.
The URL says 2023 (though the Papercall page does say 2024). It's not a blocker but it could cause confusion.

2023-09-14 12:57 UTC, phrawzty commented on data/events/2024-istanbul.yml
> + # - name: propose
If the CFP is indeed open, we recommend uncommenting this line.

2023-09-14 12:57 UTC, phrawzty commented on data/events/2024-istanbul.yml
> +team_members: # Name is the only required field for team members.
The `istanbul@devopsdays.org` has `8` addresses, but there are only `4` people listed below. Please send an email to `info@devopsdays.org` with the complete list of names and email addresses of the people listed under `team_members` here so that we can make sure they line up.

2023-09-15 08:23 UTC, serhatcan commented on data/events/2024-istanbul.yml
> +cfp_link: "https://papercall.io/devopsdays-istanbul-2023" #if you have a custom link for submitting proposals, add it here. This will control the Propose menu item as well as the "Propose" button.
This is fine for now. I've created this with 2023 URL earlier, than updated the dates, but the URL can't be changed... Opened tickets to papercall but no response. Once the link is updated, we can update this one.

2023-09-15 08:23 UTC, serhatcan commented on data/events/2024-istanbul.yml
> +cfp_date_end:  2024-01-24T00:00:00+03:00 # close your call for proposals.
Yes, we usually try to keep our CFP open for at least about 3 months.

2023-09-15 08:24 UTC, serhatcan commented on data/events/2024-istanbul.yml
> +team_members: # Name is the only required field for team members.
The 8 people are correct, we'll update this. We need to get photos, social media addresses from people, will only add them by name and email for now. Thanks!

2023-09-16 15:38 UTC, developer-guy commented on data/events/2024-istanbul.yml
> + # - name: propose
makes sense, thank you!

2023-09-17 18:01 UTC, serhatcan commented
@phrawzty if this is looking good, I'll merge this but haven't done this for a while so need your confirmation. Thanks!

2023-09-19 08:17 UTC, serhatcan commented
checked and the list is the same as google so merging it now.

2023-09-19 08:17 UTC, merged