[NSH-2024] Sets TBD Event for 2024 and adds two new organizers
devopsdays/devopsdays-web pull request #13355
Opened 2023-09-25 23:02 UTC by GeoffCraig

This does two things.

1. Sets up a TBD date, we have the drive, but we don't have a date
2. Correctly cancels the 2022 event
3. Adds two new organizers!

2023-09-26 14:30 UTC, jyee requested changes
Minor changes to remove unused images.

2023-09-26 14:30 UTC, jyee commented on static/events/2024-nashville/sponsor-dod.png
You probably want to remove this.

2023-09-26 14:30 UTC, jyee commented on static/events/2024-nashville/logo.jpg
The `logo.jpg` and `logo.png` are dupes of the `logo-square.jpg` and `logo-square.png`. Can you remove the dupes? They're not too big, but every little bit helps fight against repo bloat.

2023-09-27 00:17 UTC, GeoffCraig commented on static/events/2024-nashville/sponsor-dod.png
@jyee for some reason updates to my fork aren't coming into this PR so I'm going to have to close and reopen

2023-09-27 00:17 UTC, closed without merging