[ATX-2024] Kickoff
devopsdays/devopsdays-web pull request #13370
Opened 2023-10-02 22:58 UTC by nimbinatus

Adding starter for Austin (draft until organizers settled)

2023-10-31 00:33 UTC, jyee requested changes
A few images need to be scaled down as they're quite large. Other than that, the PR is good to merge. I can squash merge when they've been updated, so you don't need to use git replace or other tricks to remove the large images from the repo.

2023-10-31 00:33 UTC, jyee commented on static/events/2024-austin/organizers/chris-b.jpg
@nimbinatus Can you size these down? 1.81MB is rather sizeable. Also worth noting that netlify doesnt create optimized images, so folks loading the page are having to download a lot just for these to get rendered as small thumbnails.

Per the [utilities docs on organizers](https://github.com/devopsdays/devopsdays-web/tree/1d3a7fdbc38d1bde477c4636dea4d61682ee9ddf/utilities#local-organizers), images should be 300px to 600px square.

2023-10-31 00:33 UTC, jyee commented on static/events/2024-austin/organizers/karl.jpg
Another large image to shrink

2023-10-31 00:33 UTC, jyee commented on static/events/2024-austin/organizers/tim.jpeg
scale down

2023-11-14 13:19 UTC, FloorD commented
@nimbinatus did you manage to resize the images, or would you like help?

2023-11-14 17:33 UTC, nimbinatus commented
> @nimbinatus did you manage to resize the images, or would you like help?

Sorry, just been buried with KubeCon NA things. I'll hopefully get to this today or tomorrow. But thank you for the offer and the reminder!

2023-11-14 17:59 UTC, nimbinatus commented on static/events/2024-austin/organizers/tim.jpeg
fixed

2023-11-14 17:59 UTC, nimbinatus commented on static/events/2024-austin/organizers/karl.jpg
fixed

2023-11-15 14:30 UTC, merged