[MDE-2024] Adding new event files for DevopsDays Medellin 2024
devopsdays/devopsdays-web pull request #13418
Opened 2023-10-20 23:38 UTC by mpinedag12

[MDE-2024] Adding new event files for DevopsDays Medellin 2024

2023-10-26 23:11 UTC, jyee requested changes
Lots of old dates from copying files from previous years.

2023-10-26 23:11 UTC, jyee commented on content/events/2024-medellin/welcome.md
> +            href="https://latiquetera.com/evento/devopsdays-medellin-2023"
This links to the 2023 registration

2023-10-26 23:11 UTC, jyee commented on content/events/2024-medellin/welcome.md
> +            href="/events/2023-medellin/contact"
This links to the 2023 organizer page.

2023-10-26 23:11 UTC, jyee commented on data/events/2024-medellin.yml
> +cfp_date_start:  2023-01-24T08:00:00-06:00 # start accepting talk proposals.
The CFP dates are all 2023. You should comment out the dates until you have correct ones for the 2024 event.

2023-11-14 13:18 UTC, FloorD commented
@mpinedag12 can you look at the changes @jyee is suggesting?

2023-11-17 19:57 UTC, mpinedag12 commented on content/events/2024-medellin/conduct.md
> +All attendees, speakers, sponsors, and volunteers at devopsdays Medellín 2022 are required to agree with the following code of conduct. Organizers will enforce this code throughout the event. We are
Date fixed.

2023-11-17 19:57 UTC, mpinedag12 commented on content/events/2024-medellin/propose.md
> +Description = "Propose a talk for devopsdays Medellín 2022"
Date fixed.

2023-11-17 19:57 UTC, mpinedag12 commented on content/events/2024-medellin/speakers.md
> +Description = "Speakers for devopsdays Medellin 2022"
Date fixed.

2023-11-17 19:57 UTC, mpinedag12 commented on content/events/2024-medellin/welcome.md
> +            href="https://latiquetera.com/evento/devopsdays-medellin-2023"
Date fixed.

2023-11-17 19:57 UTC, mpinedag12 commented on data/events/2024-medellin.yml
> +cfp_date_start:  2023-01-24T08:00:00-06:00 # start accepting talk proposals.
Date fixed.

2023-11-17 19:57 UTC, mpinedag12 commented on content/events/2024-medellin/conduct.md
> +Description = "Code of conduct for devopsdays Medellín 2022"
Date fixed.

2023-11-17 19:57 UTC, mpinedag12 commented on content/events/2024-medellin/registration.md
> +Description = "Registration for devopsdays Medellín 2021"
Date fixed.

2023-11-17 19:58 UTC, mpinedag12 commented on content/events/2024-medellin/sponsor.md
> +Description = "Sponsor devopsdays Medellin 2021"
Date fixed.

2023-11-17 19:58 UTC, mpinedag12 commented on content/events/2024-medellin/welcome.md
> +            href="/events/2023-medellin/contact"
Date fixed.

2023-12-09 14:33 UTC, adrianmoisey commented on content/events/2024-medellin/welcome.md
> +          Three days of conferences and activities.
I noticed that this says that the conference is 3 days, but only 2 dates are set.

2023-12-09 14:43 UTC, mpinedag12 commented on content/events/2024-medellin/welcome.md
> +          Three days of conferences and activities.
Fixes and setting to Two Days

2023-12-09 14:48 UTC, merged