[rdu-2024] Adding Sponsorship levels
devopsdays/devopsdays-web pull request #13423
Opened 2023-10-21 21:03 UTC by jrn00

Adding sponsorship levels (Platinum, Gold, Silver.....) to 2024-raleigh.yml

2023-10-25 12:32 UTC, jrn00 commented
Removed Josh Atwell from Organizers section.

Removed Craig Cook's contact info. He passed away a few months ago. We still want to leave his picture up as we think of a way to honor him but dont want anyone trying to contact him via twitter, etc...

2023-10-26 22:50 UTC, jyee requested changes
Needs a yaml indentation fix.

2023-10-26 22:50 UTC, jyee commented on data/events/2024-raleigh.yml
> +    level: community
You've got an extra space here which is causing the yaml parsing to think that `level` is a child attribute of `id` and the build is failing because it's invalid.

2023-10-29 22:25 UTC, shanedroid commented
This can be closed in favor for https://github.com/devopsdays/devopsdays-web/pull/13437 👍

2023-10-30 15:10 UTC, closed without merging

2023-10-30 15:10 UTC, jrn00 commented
closed in favor of #13437