[AHM-2024] Add 2024 Ahmedabad Event
devopsdays/devopsdays-web pull request #13457
Opened 2023-11-09 07:36 UTC by kaivalya97

*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

2023-11-10 17:16 UTC, jyee requested changes

2023-11-10 17:16 UTC, jyee commented on static/events/2024-ahmedabad/sponsorship-glance.JPG
The linter is failing the build because this file needs to use a lowercase extension:
static/events/2024-ahmedabad/sponsorship-glance.JPG ==> static/events/2024-ahmedabad/sponsorship-glance.jpg

2023-11-10 17:16 UTC, jyee commented on data/events/2024-ahmedabad.yaml
> +name: "2024-ahmedabad" # The name of the event. Four digit year with the city name in lower-case, with no spaces.
It looks like you've just copied the event template and populated your information. This means you're missing an event entry in the redirects file (`/static/_redirects`).
It's highly recommended that you run the [utilities script](https://github.com/devopsdays/devopsdays-web/tree/main/utilities) to add your new event.

2023-11-10 17:16 UTC, jyee commented on data/events/2024-ahmedabad.yaml
> +team_members: # Name is the only required field for team members.
Organizers should have photos or placeholder photos in `/static/events/2024-ahmedabad/organizers`. Similar to generating your event, using the utility script to add organizers will help ensure they've got everything set up correctly.

Also, remember to send an email to info@devopsdays.org with the email addresses for each of your team members. That will allow the core team to set up an email group for you and invite your team members to Slack.

2023-12-06 12:21 UTC, shar1z commented on data/events/2024-ahmedabad.yaml
> +team_members: # Name is the only required field for team members.
Update - I had a session with this team today - and ran through how the utilities wizards work, and how to get their event set up.

They should try again, working with the utilities, and will send an email with both the organizers info and venue contract info once their Hello World is successfully set up - and then I can take it with them on Slack.

2023-12-12 12:58 UTC, glasnt commented
Hello @kaivalya97! We are still waiting on the requested changes from you before we can merge this PR and make your event live. If you need any assistance, please let us know!

2023-12-14 11:11 UTC, kaivalya97 commented
Hi all, I have made some changes please review

2023-12-14 11:21 UTC, adrianmoisey commented
There seems to be something very wrong with the branch that you're working from.
123 commits, with 5440 additions doesn't seem right

2023-12-14 11:32 UTC, kaivalya97 commented
> There seems to be something very wrong with the branch that you're working from. 123 commits, with 5440 additions doesn't seem right

I think that's because of `git pull upstream main --rebase`

2023-12-14 11:34 UTC, adrianmoisey commented
> > There seems to be something very wrong with the branch that you're working from. 123 commits, with 5440 additions doesn't seem right
> 
> I think that's because of `git pull upstream main --rebase`

Could you fix it so only show the changes that you are introducing?

2023-12-14 12:16 UTC, kaivalya97 commented
Okay I'm closing this PR and creating a new one

2023-12-14 12:16 UTC, closed without merging