[SLC-2024] Add 2024 slc event
devopsdays/devopsdays-web pull request #13468
Opened 2023-11-17 09:29 UTC by Clait

Adding 2024 SLC event, initial details.

2023-11-21 05:22 UTC, jyee requested changes
Changes to past events are discouraged in order to maintain historical accuracy. Please provide an explanation as to why you're updating the 2023 event info.

2023-11-21 05:22 UTC, jyee commented on data/events/2023-salt-lake-city.yml
> -    - name: "Allia DeAngelis"
This change is to the 2023 event. Are you retroactively removing Allia because she was not actually involved in 2023 or was this change intended to be for 2024?

We generally do not like to alter past events unless there is cause, in order to maintain historical accuracy.

2023-11-21 05:22 UTC, jyee commented on data/events/2024-salt-lake-city.yml
> +name: "2024-salt-lake-city" # The name of the event. Four digit year with the city name in lower-case, with no spaces.
it looks like you've created the event by copying the files from 2023, this means you're also missing the redirect update. You'll also need to edit line 98 of the `/static/_redirects` file to point devopsdays.org/salt-lake-city to the 2024 event.

In the future, it's recommended that you use the `add_new_event.sh` script ([see details here](https://github.com/devopsdays/devopsdays-web/blob/main/utilities/README.md#events)) to ensure your event yaml is up to date and other files are properly updated.

2023-11-21 05:22 UTC, jyee commented on static/events/2023-salt-lake-city/logo-square.jpg
Is there any reason you're adding the 2020 logo to the 2023 event?

2023-11-21 05:22 UTC, jyee commented on data/events/2024-salt-lake-city.yml
> +registration_link: "https://slcdevopsdays.org/conference" # If you have a custom registration link, enter it here. This will control the Registration menu item as well as the "Register" button.
I'm getting an http 504 error from CloudFront when trying to visit the slcdevopsdays.org site. Should we hold off on merging the PR until that is resolved?

2023-11-21 05:22 UTC, jyee commented on data/events/2024-salt-lake-city.yml
> +      # image: "brett-palmer.jpg"
You've added an image for Brett, but his image here is commented out. If the intent here is to maintain uniformity (no organizer photos), then you can remove his photo from the PR.

2023-11-21 05:31 UTC, jyee commented on data/events/2024-salt-lake-city.yml
> +cfp_date_end: 2023-11-06T23:59:59-06:00 # close your call for proposals.
These CFP dates are in the past. Did you already run an open CFP?
In the future, we recommend getting your PR in earlier, as the main devopsdays.org website receives a lot of traffic and would help you get more visibility and submissions to your CFP.

2023-11-21 18:00 UTC, ih-cweeks commented on data/events/2023-salt-lake-city.yml
> -    - name: "Allia DeAngelis"
Correct, she was not involved and we missed updating the page.

2023-11-21 18:01 UTC, ih-cweeks commented on data/events/2024-salt-lake-city.yml
> +name: "2024-salt-lake-city" # The name of the event. Four digit year with the city name in lower-case, with no spaces.
noted, thanks!

2023-11-21 18:02 UTC, ih-cweeks commented on static/events/2023-salt-lake-city/logo-square.jpg
We apparently missed adding the square version - but good catch. This is actually the 2023 logo with a typo, as we cancelled the 2020 event and then updated the logo.  Will update.

2023-11-21 18:04 UTC, ih-cweeks commented on data/events/2024-salt-lake-city.yml
> +registration_link: "https://slcdevopsdays.org/conference" # If you have a custom registration link, enter it here. This will control the Registration menu item as well as the "Register" button.
It's been up and down during maint, will let my fellow organizers know. Thanks!

2023-11-21 20:16 UTC, ih-cweeks commented on data/events/2024-salt-lake-city.yml
> +      # image: "brett-palmer.jpg"
Will do.

2023-11-21 20:16 UTC, ih-cweeks commented on data/events/2024-salt-lake-city.yml
> +cfp_date_end: 2023-11-06T23:59:59-06:00 # close your call for proposals.
Yes, CFP just closed this month.

2023-11-21 20:20 UTC, Clait commented on data/events/2023-salt-lake-city.yml
> -    - name: "Allia DeAngelis"
Correct, she was not involved and we missed updating the page.

2023-11-21 20:21 UTC, Clait commented on static/events/2023-salt-lake-city/logo-square.jpg
We apparently missed adding the square version - but good catch. This is actually the 2023 logo with a typo, as we cancelled the 2020 event and then updated the logo. Will update.

2023-11-21 20:21 UTC, Clait commented on data/events/2024-salt-lake-city.yml
> +registration_link: "https://slcdevopsdays.org/conference" # If you have a custom registration link, enter it here. This will control the Registration menu item as well as the "Register" button.
It's been up and down during maint, will let my fellow organizers know. Thanks!

2023-11-21 20:22 UTC, Clait commented on data/events/2024-salt-lake-city.yml
> +cfp_date_end: 2023-11-06T23:59:59-06:00 # close your call for proposals.
Yes, CFP just closed this month.

2023-11-21 20:23 UTC, Clait commented on data/events/2024-salt-lake-city.yml
> +name: "2024-salt-lake-city" # The name of the event. Four digit year with the city name in lower-case, with no spaces.
Good to know, thanks Jason.

2023-12-12 13:00 UTC, glasnt commented
Hi @Clait. We're still waiting for the requested changes to this PR before we can merge. If you need any help, please let us know!

2023-12-20 06:50 UTC, Clait commented
> Hi @Clait. We're still waiting for the requested changes to this PR before we can merge. If you need any help, please let us know!

Apologies for the delays.  Requested updates done.  Please review, thanks!

2023-12-28 18:32 UTC, Clait commented
@jyee , are you around this week to re-review the changes as requested?

2024-01-04 20:12 UTC, Clait commented
> Hi @Clait. We're still waiting for the requested changes to this PR before we can merge. If you need any help, please let us know!

Hi, all changes requested should have been completed. Please let me know if there's anything else we can do to get this merged.  Thanks!

2024-01-04 20:39 UTC, mattstratton approved these changes

2024-01-04 20:39 UTC, merged

2024-01-04 23:02 UTC, Clait commented
Thanks @mattstratton