[BHE] Add 2024 event
devopsdays/devopsdays-web pull request #13479
Opened 2023-11-26 00:47 UTC by Zandler

Add 2024 event for Belo Horizonte.

2023-11-27 22:16 UTC, jyee requested changes
The files appear to be copied from a previous event and need changes. Also, this PR will need to include an update to the `/static/_redirects` file ([see line 10](https://github.com/devopsdays/devopsdays-web/blob/main/static/_redirects#L10)).

In the future, we strongly recommend that you use the `add_new_event.sh` script in the `/utilities` folder to generate the event. This script will ensure that you're not missing values or updates to related files such as the _redirects. More info at https://github.com/devopsdays/devopsdays-web/tree/main/utilities

2023-11-27 22:16 UTC, jyee commented on content/events/2024-belo-horizonte/propose.md
> +Description = "Propose a talk for devopsdays London 2024"
Looks like you have copied files from the London event.

2023-11-27 22:16 UTC, jyee commented on content/events/2024-belo-horizonte/sponsor.md
> +Description = "Sponsor DevOpsDays London 2024"
Again, wrong city here.

2023-11-27 22:16 UTC, jyee commented on data/events/2024-belo-horizonte.yml
> +startdate:  2024-09-28T00:00:00-03:00
You'll need to set times for both the `startdate` and `enddate` otherwise the site generator will think it starts and ends at the same time and do some odd things on the day of your event.

Something more like `2024-09-28T09:00:00-03:00` for the start and `2024-09-28T18:00:00-03:00` for the end.

2023-11-27 22:16 UTC, jyee commented on data/events/2024-belo-horizonte.yml
> +organizer_email: "organizers-belo-horizonte-2019@devopsdays.org" # Put your organizer email address here
This is an old email. It should be updated to belo-horizonte@devopsdays.org

Also, it looks like there are members who were involved in the previous devopsdays Belo Horizonte and are no longer involved. Can you email info@devopsdays.org with the email addresses for all of these organizers and we can remove anyone who is not an organizer.

2023-11-27 22:16 UTC, jyee commented on static/events/2024-belo-horizonte/organizers/dalton-strauss.jpg
Dalton is not listed as an organizer. Is this photo needed or do you need to add him to the organizer list?

2023-11-27 22:16 UTC, jyee commented on static/events/2024-belo-horizonte/organizers/diego-f-duarte.jpg
Diego is not listed as an organizer. Remove photo or add to the organizer list.

2023-11-27 22:16 UTC, jyee commented on static/events/2024-belo-horizonte/organizers/marco-antonio.jpg
Marco is not listed as an organizer. Remove photo or add to the organizer list.

2023-11-27 22:16 UTC, jyee commented on static/events/2024-belo-horizonte/organizers/rafael-gomes.jpg
Rafael is not listed as an organizer. Remove photo or add to the organizer list.

2024-02-16 21:02 UTC, phrawzty commented
This appears to be superseded by #13685. Can anybody confirm? Thanks!

2024-02-17 20:54 UTC, phrawzty commented
Confirmed in #13685. Closing this PR.

2024-02-17 20:54 UTC, closed without merging