[MTL-2024 ] v1 for the Montreal 2024 event
devopsdays/devopsdays-web pull request #13476
Opened 2023-11-24 13:25 UTC by sebagomez

Sorry about the extra commits... will rebase right after this

2023-11-27 22:01 UTC, jyee requested changes
One minor change to scale down Sydney's photo. Once that's updated we can squash merge (i.e. no need to mess with commits to remove the larger photo)

You might also want to consider scaling down (or lowering the jpg quality level) the `montreal-background.jpg` as it's 2.71MB.

2023-11-28 22:27 UTC, jyee requested changes

2023-11-28 22:27 UTC, jyee commented on utilities/add_speakers.sh
This looks unrelated and possibly a dupe of the existing linkedin functionality. Please submit in a separate PR if you'd like to make this change.

Once removed, we can squash merge to get the event up.

2023-11-29 01:26 UTC, sebagomez commented
Did I do it right?Please let me know Le 28 nov. 2023 à 17:27, Jason Yee ***@***.***> a écrit :﻿
@jyee requested changes on this pull request.



On utilities/add_speakers.sh:
This looks unrelated and possibly a dupe of the existing linkedin functionality. Please submit in a separate PR if you'd like to make this change.
Once removed, we can squash merge to get the event up.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-11-29 16:15 UTC, merged