[NBI-2024] added new event for devopsdays Nairobi and organizers details.
devopsdays/devopsdays-web pull request #13513
Opened 2023-12-13 20:32 UTC by alvo254

*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

2023-12-14 08:01 UTC, adrianmoisey commented
There seem to be extra files in `content/events/2024-nairobi/yyyy-city/*` that are unneeded

2023-12-14 08:01 UTC, adrianmoisey commented on data/events/2024-nairobi.yml
> +    level: gold
This is a sample, are you sure you want it?

2023-12-15 16:49 UTC, mattstratton requested changes

2023-12-15 16:49 UTC, mattstratton commented on data/events/2024-nairobi.yml
> +startdate:  June 1 # The start date of your event. Leave blank if you don't have a venue reserved yet.
please note that the date fields need to be set in in unquoted 2024-MM-DDTHH:MM:SS+TZ:TZ 

like this: `2019-01-04T00:00:00+02:00`

this is failing on build bc of how startdate and enddate are set

2023-12-19 17:52 UTC, closed without merging