[AHM-2024] Add 2024 Ahmedabad Event
devopsdays/devopsdays-web pull request #13530
Opened 2023-12-20 06:16 UTC by kaivalya97

Initial details.

2023-12-21 13:57 UTC, shar1z commented
This looks good to me - I'm just going to ask for a second pair of eyes on this.
Don't forget to send the email to info@ to get your emails added to the distribution list and Slack.

2023-12-21 14:03 UTC, mattstratton requested changes
Please update to use the devopsdays.org email alias for this!

2023-12-21 14:03 UTC, mattstratton commented on data/events/2024-ahmedabad.yaml
> +organizer_email: "devopsahmedabad@gmail.com" # Put your organizer email address here
this email address needs to be the `@devopsdays.org` email alias

2023-12-23 11:59 UTC, kaivalya97 commented on data/events/2024-ahmedabad.yaml
> +organizer_email: "devopsahmedabad@gmail.com" # Put your organizer email address here
I have updated it based on other events but I don't know if this alias is already created or not.

2023-12-23 13:38 UTC, mattstratton commented
Have you sent the email to info@devopsdays.org requesting it be created?

2023-12-28 08:36 UTC, shar1z commented
@kaivalya97 - this is fine to merge I think - except that you should note that the preferred email address to use is 
ahmedabad@devopsdays.org 
I have created an alias with this email address - in order to get your event launched.
But in your next edit - update the email to the city@devopsdays.org

@mattstratton I believe this is OK to merge

2023-12-28 11:37 UTC, mattstratton approved these changes

2023-12-28 11:38 UTC, mattstratton commented
lgtm

2023-12-28 11:46 UTC, merged

2023-12-28 11:47 UTC, shar1z commented
@kaivalya97 - this has been merged - feel free to delete the branch.