[SP-2024] Add redirect to CFP page and rename event folder
devopsdays/devopsdays-web pull request #13531
Opened 2023-12-20 14:46 UTC by strund3r

Rename event file and folder from `2024-saopaulo` to `2024-sao-paulo` to maintain the same pattern from previous years and to fix the redirect from [devopsdays.org/sao-paulo](url).

2023-12-20 15:23 UTC, gomex approved these changes
LGTM

2023-12-21 04:51 UTC, adrianmoisey commented on static/_redirects
> +/sao-paulo/cfp		https://talks.devopsdays.org/devopsdays-sao-paulo-2024/cfp 302
I think order matters here and `/sao-paulo/cfp` needs to be before `/sao-paulo/*`

2023-12-23 13:41 UTC, mattstratton commented on static/_redirects
> +/sao-paulo/cfp		https://talks.devopsdays.org/devopsdays-sao-paulo-2024/cfp 302
Just to confirm for future reference, [yes it does](https://docs.netlify.com/routing/redirects/).

2023-12-23 13:51 UTC, mattstratton requested changes
Please change the order of the redirect rules so that the /cfp one comes first or it won’t work 

https://github.com/devopsdays/devopsdays-web/pull/13531#discussion_r1433494879

2023-12-23 13:56 UTC, strund3r commented on static/_redirects
> +/sao-paulo/cfp		https://talks.devopsdays.org/devopsdays-sao-paulo-2024/cfp 302
Fixed

2023-12-23 14:16 UTC, merged