[NRB-2024] NAIROBI 2024 - INITIAL PR
devopsdays/devopsdays-web pull request #13542
Opened 2023-12-29 14:13 UTC by alvo254

*Please title your pull request in this format: The event name and year in the title of the PR, along with a description of what is being changed, i.e., `[CHI-2019] Add Bluth Company as a sponsor`*

If you are adding or removing organisers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so we can update Slack and the mailing list.

2024-01-02 13:46 UTC, adrianmoisey commented
As mentioned in the previous PRs ([here](https://github.com/devopsdays/devopsdays-web/pull/13513#issuecomment-1855358123)) the `yyyy-city` files are not needed and can be deleted.

2024-01-02 13:48 UTC, adrianmoisey commented on data/events/2024-nairobi.yml
> +enddate:  2024-06-01T18:00:00+00:00 # The end date of your event. Leave blank if you don't have a venue reserved yet.
Are these days correct?
Over in slack ([here](https://devopsdays.slack.com/archives/C05MNP1FV52/p1698737499689319)) the date mentioned was 6th April 2024

2024-01-04 06:13 UTC, alvo254 commented on data/events/2024-nairobi.yml
> +enddate:  2024-06-01T18:00:00+00:00 # The end date of your event. Leave blank if you don't have a venue reserved yet.
Yes, the dates are correct you will receive an update on slack.

2024-01-05 23:09 UTC, glasnt commented on data/events/2024-nairobi.yml
> +    github: "https://github.com/Nabhany"
The `github` value just needs to be the GitHub username
```suggestion
    github: "Nabhany"
```

2024-01-05 23:10 UTC, glasnt commented on data/events/2024-nairobi.yml
> +    github: "devopsdays"
This is our github :) If Ivy has an account, please add it
```suggestion
    github: ""
```

2024-01-05 23:12 UTC, glasnt commented on data/events/2024-nairobi.yml
> +city: "NAIROBI" # The displayed city name of the event. Capitalize it.
As a stylistic choice, we tend to have cities use Title case, not allcaps
```suggestion
city: "Nairobi" # The displayed city name of the event. Capitalize it.
```

2024-01-05 23:13 UTC, glasnt commented on data/events/2024-nairobi.yml
> +event_twitter: "devopsdaysnairobi" # Change this to the twitter handle for your event such as devopsdayschi or devopsdaysmsp
This account doesn't exist. I can see `devopsdaysNRB` is an account, is that the correct one?

2024-01-05 23:16 UTC, glasnt commented on data/events/2024-nairobi.yml
> +team_members: # Name is the only required field for team members.
There's two more members of your team that haven't been added here, according to your emails.

2024-01-05 23:16 UTC, glasnt requested changes
There are a few updates that are needed, and an onboarding call (if not already organised).

2024-01-08 09:30 UTC, phrawzty commented
> There are a few updates that are needed, and an onboarding call (if not already organised).

My understanding is that @adrianmoisey already onboarded them. Confirm / deny, Adrian?

2024-01-08 09:32 UTC, adrianmoisey commented
> > There are a few updates that are needed, and an onboarding call (if not already organised).
> 
> My understanding is that @adrianmoisey already onboarded them. Confirm / deny, Adrian?

Correct, we've done the onboarding call.

2024-01-09 07:02 UTC, alvo254 commented on data/events/2024-nairobi.yml
> +team_members: # Name is the only required field for team members.
Just one more member.

2024-01-09 14:10 UTC, jyee commented on data/events/2024-nairobi.yml
> +enddate:  2024-06-01T18:00:00+00:00 # The end date of your event. Leave blank if you don't have a venue reserved yet.
Also, these times are set to +00:00, meaning they are GMT timezone. Nairobi is GMT+3, so you may want to update the dates to reflect that. e.g. `startdate: 2024-06-01T08:00:00+03:00`.

2024-01-09 17:55 UTC, adrianmoisey commented on data/events/2024-nairobi.yml
> +team_members: # Name is the only required field for team members.
It's two. We originally got 7 names on Aug 2, 2023, and an additional name on Mon, 11 Dec 2023.

We need the list of names we receive to match the pull request.

2024-01-11 17:34 UTC, adrianmoisey commented on data/events/2024-nairobi.yml
> +enddate:  2024-06-01T18:00:00+00:00 # The end date of your event. Leave blank if you don't have a venue reserved yet.
Fixed in https://github.com/devopsdays/devopsdays-web/pull/13542/commits/f3ff9e0f5c6845efc64dd6d8e539333cb73da29d

2024-01-11 17:35 UTC, adrianmoisey commented on data/events/2024-nairobi.yml
> +    github: "https://github.com/Nabhany"
Fixed in https://github.com/devopsdays/devopsdays-web/pull/13542/commits/1c0018a8a3bc0d24f2c3afd5653dd638712c615f

2024-01-11 17:35 UTC, adrianmoisey commented on data/events/2024-nairobi.yml
> +    github: "devopsdays"
Fixed in https://github.com/devopsdays/devopsdays-web/pull/13542/commits/1c0018a8a3bc0d24f2c3afd5653dd638712c615f

2024-01-11 17:35 UTC, adrianmoisey commented on data/events/2024-nairobi.yml
> +city: "NAIROBI" # The displayed city name of the event. Capitalize it.
Fixed in https://github.com/devopsdays/devopsdays-web/pull/13542/commits/1c0018a8a3bc0d24f2c3afd5653dd638712c615f

2024-01-11 17:35 UTC, adrianmoisey commented on data/events/2024-nairobi.yml
> +event_twitter: "devopsdaysnairobi" # Change this to the twitter handle for your event such as devopsdayschi or devopsdaysmsp
Fixed in https://github.com/devopsdays/devopsdays-web/pull/13542/commits/1c0018a8a3bc0d24f2c3afd5653dd638712c615f

2024-01-11 17:40 UTC, adrianmoisey commented
This PR is getting close.

At the moment there are issues with the team members.

From the emails we've received, it seems like the PR is missing:
- Alvin Ndungu
- Emma Nyakio

There is also an extra person in this pull request:
- Emmah Gachoki

Can you please reconcile this?

2024-01-14 08:17 UTC, merged