[KRK-2024] Krakow 2024 - Initial PR
devopsdays/devopsdays-web pull request #13541
Opened 2023-12-29 13:06 UTC by ivellios

**This is a draft** - missing links to the proper CFP and registration pages as these are blocked by the Core Team accept for the event and update of the mailing list/group.

- Initial information (date/location) added for Kraków 2024 event
- Updated list of organizers along with photos

2024-01-03 11:39 UTC, adrianmoisey commented on data/events/2024-krakow.yml
> +enddate: 2023-03-13T23:59:59+02:00
```suggestion
startdate: 2024-03-12T00:00:00+02:00
enddate: 2024-03-13T23:59:59+02:00
```

2024-01-03 11:40 UTC, adrianmoisey commented on data/events/2024-krakow.yml
> +enddate: 2023-03-13T23:59:59+02:00
The page doesn't get added to the front page of DOD at the moment, as these dates are in the past.

2024-01-03 11:41 UTC, adrianmoisey commented
I added `awaiting-email-to-info` as there is an email thread about getting the correct URL for the CFP.

2024-01-03 11:42 UTC, adrianmoisey commented on static/events/2024-krakow/organizers/jakub_barc.png
Could you convert this file to a smaller JPEG?

2024-01-06 11:08 UTC, ivellios commented on static/events/2024-krakow/organizers/jakub_barc.png
Sure can do!

2024-01-09 14:00 UTC, jyee requested changes
One additional minor change: Please update the `/static/_redirects` file (line 63) to redirect `/krakow` to this event. It currently directs to the 2020 event.

In the future, we recommend using the `add_new_event.sh` script in the [Utilities](https://github.com/devopsdays/devopsdays-web/tree/main/utilities) directory to generate your events (that will ensure they have the proper site updates).

Also, per the email exchange, I think that the `2024-krakow.yml` file needs the CFP info, but this is not a blocker if you intend to add that later for some reason.

Aside from this, everything else appears to be ok, so mark the PR as "reviewable" (it is currently "draft") and someone from the core team can merge it.

2024-01-09 19:04 UTC, ivellios commented
@jyee - I have addressed your notes. Thank you for the suggestions.

We have also pushed the date of the event and had to change the location.
I mark it as ready for review.

2024-01-11 17:43 UTC, merged