[DC-2024] Initialize the Washington DC 2024 event
devopsdays/devopsdays-web pull request #13604
Opened 2024-01-21 18:52 UTC by gallimorej

Get everything set up for the Washington DC event.

Used the `add-new-event.sh` script to get it started.

Copied info from 2023 event as appropriate.

2024-01-22 21:01 UTC, gallimorej commented
Also... I sent an email to info-at-devopsdays.org with all the info for updates to the email list and the Slack channel.

2024-01-23 15:01 UTC, phrawzty requested changes
Looks great! Just one item to address. 🙂

2024-01-23 15:01 UTC, phrawzty commented on data/events/2024-washington-dc.yml
> +team_members: # Name is the only required field for team members.
You have 12 people in your mailing list (as per the email you sent), but only ten listed here. Please either add the other two people to this section, or remove them from the mailing list.

2024-01-24 02:24 UTC, gallimorej commented on data/events/2024-washington-dc.yml
> +team_members: # Name is the only required field for team members.
Thanks for the catch there. I updated the YAML file (should have 11 team members) and resent the email (with 11 team members) so they should match now.

2024-01-25 16:05 UTC, gallimorej commented
@phrawzty I think I reconciled everything (YAML and email). Ready for a re-review when you have a moment.

2024-01-25 16:09 UTC, phrawzty approved these changes

2024-01-25 16:09 UTC, merged