Update PULL_REQUEST_TEMPLATE
devopsdays/devopsdays-web pull request #13639
Opened 2024-02-05 09:44 UTC by yvovandoorn

Be specific on making sure the default text is removed and what should be put in the body portion of the PR.

2024-02-05 12:19 UTC, mattstratton requested changes

2024-02-05 12:19 UTC, mattstratton commented on .github/PULL_REQUEST_TEMPLATE
> +*Please read take into consideration of the following:*
```suggestion
*Please read and take into consideration the following:*
```

2024-02-05 13:42 UTC, phrawzty commented on .github/PULL_REQUEST_TEMPLATE
> +* If you are adding or removing organi[s/z]ers, please email info@devopsdays.org with the details of who is being added and removed, along with the full names and email addresses of the new team, so
While I _love_ messing around with this sort of thing as a lark<sup>1</sup>, for better or worse, I think the standard is `en_US` spelling, no?

<sup>1</sup> `The first DevOpsDays was held in G[h]<a|e>n<d|t>`

2024-02-05 17:02 UTC, bridgetkromhout commented on .github/PULL_REQUEST_TEMPLATE
> +Finally, if you left this text in your PR, then it appears you didn't read it. Please remove this in the PR you are submitting.
Do we want to give the appearance of unkindness? Perhaps just stating "Please ensure you have replaced this default text" would suffice?

2024-02-05 17:09 UTC, phrawzty commented on .github/PULL_REQUEST_TEMPLATE
> +Finally, if you left this text in your PR, then it appears you didn't read it. Please remove this in the PR you are submitting.
Yeah there's no reason to get aggro 😆

2024-02-06 12:12 UTC, mattstratton commented on .github/PULL_REQUEST_TEMPLATE
> +Finally, if you left this text in your PR, then it appears you didn't read it. Please remove this in the PR you are submitting.
I went back and forth on this one; i read it as passive aggressive at first, and now I think it is more in the spirit of "this is why we say to remove the text", but impact > intent so probably agree with Bridget

2024-02-06 12:12 UTC, mattstratton commented on .github/PULL_REQUEST_TEMPLATE
> +Finally, if you left this text in your PR, then it appears you didn't read it. Please remove this in the PR you are submitting.
that said, we have said "please remove this text" for years and nobody does it, which is why it got aggro here :D

2024-02-06 12:13 UTC, mattstratton commented on .github/PULL_REQUEST_TEMPLATE
> +Finally, if you left this text in your PR, then it appears you didn't read it. Please remove this in the PR you are submitting.
one other solution (which might not work) is we can probably write some kind of PR linting rule that will block the PR if the default text was not removed (it'll be pretty easy to match on something like "Bluth Company" which won't be in any legit PRs)

2024-02-06 12:15 UTC, mattstratton commented on .github/PULL_REQUEST_TEMPLATE
> +Finally, if you left this text in your PR, then it appears you didn't read it. Please remove this in the PR you are submitting.
https://github.com/orgs/community/discussions/84771

2024-02-06 12:26 UTC, mattstratton commented
I actually put in a PR that will test the pull requests against default text being included (it just tests for the word `"Bluth"` but that should suffice) and that seems to be working (not yet merged)

https://github.com/devopsdays/devopsdays-web/pull/13643

2024-02-06 12:26 UTC, mattstratton commented on .github/PULL_REQUEST_TEMPLATE
> +Finally, if you left this text in your PR, then it appears you didn't read it. Please remove this in the PR you are submitting.
okay that was easy https://github.com/devopsdays/devopsdays-web/pull/13643

2024-02-06 15:49 UTC, mattstratton commented on .github/PULL_REQUEST_TEMPLATE
> +Finally, if you left this text in your PR, then it appears you didn't read it. Please remove this in the PR you are submitting.
i think this can probably be softened up now that #13643 has been merged

2024-02-07 07:47 UTC, yvovandoorn commented on .github/PULL_REQUEST_TEMPLATE
> +Finally, if you left this text in your PR, then it appears you didn't read it. Please remove this in the PR you are submitting.
The intent was not to be passive-aggressive. It is hard to come up with words on how to tell folks (kindly) to remove the default text

2024-02-07 07:53 UTC, yvovandoorn commented
I updated the message to be much less aggro and far more approachable!

2024-02-08 05:51 UTC, glasnt approved these changes

2024-02-08 13:04 UTC, phrawzty requested changes

2024-02-08 13:04 UTC, phrawzty commented on .github/PULL_REQUEST_TEMPLATE
> +- Remove this text and replace with a high level of the changes (e.g. 'Added 10 new speakers, Added 6 sponsors').
```suggestion
- Title your pull request in this format: `[PLACE-YEAR] Brief description of the proposed change`. For example: `[CHI-2024] Add Bluth Company as a sponsor`
- Remove _this default text_ from the PR description, and replace it with a summary of the changes (e.g. 'Added 10 new speakers, Added 6 sponsors, Added emojis to CFP page').
```

2024-02-16 09:11 UTC, phrawzty approved these changes

2024-02-16 14:38 UTC, merged