[BHE-2024] Adding current organizers and setting up the event page
devopsdays/devopsdays-web pull request #13685
Opened 2024-02-16 14:39 UTC by shescloud

Adding current organizers and setting up the event page

2024-02-16 21:03 UTC, phrawzty commented
This appears to supersede #13479. Can anybody confirm?

2024-02-17 14:53 UTC, shescloud commented
> This appears to supersede #13479. Can anybody confirm?

Yeah, confirmed! I recreated the event and added the current organization. The organization underwent restructuring. I sent an email to info@devopsdays.org talking about the new organization

2024-02-18 20:08 UTC, phrawzty requested changes

2024-02-18 20:08 UTC, phrawzty commented on content/events/2024-belo-horizonte/propose.md
> + Aqui estão alguns fatores que consideramos ao tentar montar o melhor programa possível para o nosso público local:
This page does not indicate how to actually submit a proposal. That's fine as long as you're not linking to it—but you are. Either include submission details here, or don't link to this file.

2024-02-18 20:08 UTC, phrawzty commented on data/events/2024-belo-horizonte.yml
> +organizer_email: "" # Put your organizer email address here
This needs to be populated as it is used in templates elsewhere (the sponsor page, for example).

```suggestion
organizer_email: "belo-horizonte@devopsdays.org" # Put your organizer email address here
```

2024-02-18 20:08 UTC, phrawzty commented on data/events/2024-belo-horizonte.yml
> +    url: /events/2024-belo-horizonte/propose
If you're ready to accept proposals, you'll need to set the `cfp_date` variables on lines 17–19 (you'll also want to include submission details in that page). If you're _not_ ready to accept proposals, you should comment this out.

2024-02-18 20:39 UTC, phrawzty approved these changes

2024-02-18 20:39 UTC, phrawzty commented on data/events/2024-belo-horizonte.yml
> +    url: /events/2024-belo-horizonte/propose
We're making code changes to the site and in an effort to speed things along, I'm going to go ahead and comment this out for now.
```suggestion
  # - name: requisitos para as palestras
  #   url: /events/2024-belo-horizonte/propose 
```

2024-02-18 20:39 UTC, phrawzty commented on content/events/2024-belo-horizonte/propose.md
> + Aqui estão alguns fatores que consideramos ao tentar montar o melhor programa possível para o nosso público local:
My comment above stands, but as I'm commenting out the linked element from your welcome page, it can be addressed in a future PR.

2024-02-18 20:39 UTC, phrawzty commented on data/events/2024-belo-horizonte.yml
> +team_members: # Name is the only required field for team members.
You _will_ need to fix this in future PR, but as we're trying to close out the open requests…

2024-02-18 20:50 UTC, merged