[HOU-2024] Update Sponsor Info
devopsdays/devopsdays-web pull request #13717
Opened 2024-02-21 21:53 UTC by mabaums

- Update Sponsor inconsistencies with location/year/time.
- Add Paypal sponsor links.

2024-02-22 08:01 UTC, phrawzty requested changes

2024-02-22 08:01 UTC, phrawzty commented on content/events/2024-houston/sponsor.md
> +    <dd> &lt Details coming in May &rt </dd>
```suggestion
    <dd>&lt; Details coming in May &rt;</dd>
```

2024-02-24 15:24 UTC, skryukova commented
@mattstratton Thank you for getting the fix in! 
@phrawzty Would it be possible to merge this in now?

2024-02-24 20:15 UTC, phrawzty approved these changes

2024-02-24 20:15 UTC, merged