[POR-2024] Create DevOpsDays Portugal 2024
devopsdays/devopsdays-web pull request #13745
Opened 2024-02-27 19:00 UTC by joaorafaelpinto

This pull request creates the DevOpsDays Portugal 2024 event.

2024-02-28 10:54 UTC, phrawzty requested changes

2024-02-28 10:54 UTC, phrawzty commented on data/events/2024/portugal/main.yml
> +team_members: # Name is the only required field for team members.
Hello! Please send an email to [info@devopsdays.org](mailto:info@devopsdays.org) with the names, email addresses, and respective organisations of your local team for 2024. The list in `main.yml` and the list you send by email must be identical. 🙂 We'll modify the portugal@ distribution list and Slack composition accordingly.

2024-02-28 10:54 UTC, phrawzty commented on content/events/2024-portugal/registration.md
> +    <p>Other then that, we currenlty have some tickets reserved for sponsors and volunteers, if that is an option you want to consider:</p>
Are you sure that you're sold out already? This feels like it might be a copy/paste from your previous event. :)

2024-02-28 10:54 UTC, phrawzty commented on data/events/2024/portugal/main.yml
> +  - name: program
You don't currently have a program page, so comment this out until you do. :)
```suggestion
#  - name: program
```

2024-02-28 10:54 UTC, phrawzty commented on data/events/2024/portugal/main.yml
> +location_address: #Optional - use the street address of your venue. This will show up on the welcome page if set.
You appear to have details in `location.md`, so please reflect them here (assuming `location.md` is accurate). For example:

```suggestion
location: # Defaults to city, but you can make it the venue name.
#
location_address: "EDIFÍCIO DA ALFÂNDEGA, R. Nova da Alfândega, 4050-430 Porto"
```

Fwiw, this feels like you copied a `main.yml` from a previous year, because the template has changed; for example, `coordinates:` isn't used anymore…

2024-02-28 10:54 UTC, phrawzty commented on data/events/2024/portugal/main.yml
> +  - name: speakers
You don't currently have a speakers page, so comment this out until you do. 
```suggestion
#  - name: speakers
```

2024-02-28 10:54 UTC, phrawzty commented on content/events/2024-portugal/volunteer.md
> +(volunteer signup is now closed)
It's closed? Are you sure?

2024-02-28 10:54 UTC, phrawzty commented on content/events/2024-portugal/sponsor.md
> +      <td><s>5000 EUR</td>
These are sold out but you haven't listed any sponsors for your event yet?

2024-02-28 10:54 UTC, phrawzty commented on content/events/2024-portugal/conduct.md
> ++++
Fwiw, there is a Portuguese-language COC template as well, in case that's useful.

2024-02-28 10:57 UTC, phrawzty commented
This feels a _lot_ like you used `add_new_event.sh` and then just copied over all the files from a previous year. We really do not recommend doing that. You can fix things here but my _strong suggestion_ is to close this PR and open a fresh one that you update to reflect current reality. If you need help with that, please let us know in `#website` on the Slack. 👍 

Either way, you'll need to send that local organiser update email, however.

2024-03-01 11:54 UTC, phrawzty commented
Closing as per email from `Elisete Cruz`. We'll keep our eyes open for a fresh PR. 😄

2024-03-01 11:54 UTC, closed without merging

2024-03-06 18:56 UTC, joaorafaelpinto commented
Thank you for your review @phrawzty, I'm aware that Elisete Cruz already sent the e-mail with the organizers list and we will send a new PR taking into consideration all your comments above.