[Campinas-2024]  Adding ediction dod São Paulo 2024
devopsdays/devopsdays-web pull request #13768
Opened 2024-03-01 12:30 UTC by GiovanaNp1

This is the first commit for starting the jobs in DevOpsDays Campinas

2024-03-01 13:44 UTC, phrawzty requested changes

2024-03-01 13:44 UTC, phrawzty commented on data/events/2024/campinas/main.yml
> +organizer_email: "devopsdays.campinas@gmail.com" # Put your organizer email address here
This _must_ be your `@devopsdays.org` address.

```suggestion
organizer_email: "campinas@devopsdays.org" # Put your organizer email address here
```

2024-03-01 13:44 UTC, phrawzty commented on data/events/2024/campinas/main.yml
> +team_members: # Name is the only required field for team members.
The list here doesn't appear to line up with the current `campinas@devopsdays.org` distribution list. Please send an email to info@devopdays.org with the full list of names and email addresses of your local team (it must match this list here in `main.yml`).

2024-03-03 14:12 UTC, GiovanaNp1 commented on data/events/2024/campinas/main.yml
> +team_members: # Name is the only required field for team members.
Hello @phrawzty i try send email for [info@devopdays.org](mailto:info@devopdays.org) but i I received this response

![Uploading image.png…]()

2024-03-05 14:39 UTC, GiovanaNp1 commented on data/events/2024/campinas/main.yml
> +team_members: # Name is the only required field for team members.
@phrawzty  could help me with this topic?

2024-03-05 14:43 UTC, phrawzty commented on data/events/2024/campinas/main.yml
> +team_members: # Name is the only required field for team members.
@GiovanaNp1 You spelled `devopsdays` incorrectly—you're missing the `s` in `ops`. 🫢

2024-03-06 00:49 UTC, GiovanaNp1 commented on data/events/2024/campinas/main.yml
> +team_members: # Name is the only required field for team members.
Sorry my mistake, i'm send now the update

2024-03-07 12:29 UTC, gomex requested changes
Pode confirmar se ja tem local? A data só pode ser colocada com local confirmado!

2024-03-07 12:29 UTC, gomex commented on data/events/2024/campinas/main.yml
> +enddate: 2024-09-21T23:59:59-03:00 # The end date of your event. Leave blank if you don't have a venue reserved yet.
A data só pode ser colocada no PR quando tiver o local confirmado.

2024-03-07 13:46 UTC, phrawzty commented on data/events/2024/campinas/main.yml
> +team_members: # Name is the only required field for team members.
n.b. Still waiting for clarity on team membership composition.

2024-03-10 22:53 UTC, closed without merging

2024-03-10 22:54 UTC, GiovanaNp1 commented
I'm canceling this PR to get the new information I need