[NRB-2024]-added a sponsor
devopsdays/devopsdays-web pull request #13974
Opened 2024-04-19 12:30 UTC by alvo254

Addition of kube events and kube careers as a media sponsor to Nairobi(NRB)

2024-04-19 13:52 UTC, phrawzty requested changes

2024-04-19 13:52 UTC, phrawzty commented on data/events/2024/nairobi/main.yml
> +    url: https://kube.events/
Items listed under `sponsors:` must refer to sponsor files. In other words, you need to also include:
- A sponsor definition for each under `data/sponsors/`
- A logo for each sponsor under `static/img/sponsors/`

As you can see in [the preview](https://deploy-preview-13974--devopsdays-web.netlify.app/events/2024-nairobi/welcome/), which the pages are rendered, the sponsor entries you've listed do not appear.

Finally, note that sponsor `id`s cannot contain spaces, as they refer to filenames.

For more details, please see the [related documentation](https://github.com/devopsdays/devopsdays-web/blob/main/utilities/README.md#sponsors).

2024-04-23 07:06 UTC, alvo254 commented on data/events/2024/nairobi/main.yml
> +    url: https://kube.events/
Done. Thanks

2024-04-23 14:56 UTC, phrawzty approved these changes

2024-04-23 14:56 UTC, merged