[FOR-2024] - add Fortaleza event
devopsdays/devopsdays-web pull request #13993
Opened 2024-04-24 02:23 UTC by ana-aguilar7

*Please read and take into consideration the following:*
- Title your pull request in this format: `[PLACE-YEAR] Brief description of the proposed change`. For example: `[CHI-2024] Add Bluth Company as a sponsor`
- Remove _this default text_ from the PR description, and replace it with a summary of the changes (e.g. 'Added 10 new speakers, Added 6 sponsors, Added emojis to CFP page').

*If you are adding or removing organizers*, send an email to info@devopsdays.org with the full names, email addresses, and organizations the added/removed persons represent. (The global team uses this information to maintain your mailing list as well as the Slack.)

Large files should go in https://github.com/devopsdays/devopsdays-assets/ . *If _this_ PR is related to an _assets_ PR*, please include a link to the latter.

Up to date guidelines for pull requests can be found in the [contributing guide](https://github.com/devopsdays/devopsdays-web/blob/main/CONTRIBUTING.md#guidelines).

2024-04-24 23:00 UTC, tutagomes commented
Hi @ana-aguilar7,

I wanted to highlight that the DevOpsDays BH team previously submitted a PR on February 18th #13685 for the event scheduled on September 28th, which was later updated two weeks ago to September 21st (#13943) . Can you confirm if you'll be aligning with this new date for the Fortaleza event?

 Thanks for your dedication and commitment to the community in making DevOpsDays happen.

2024-04-26 20:16 UTC, renat473 commented
Hello @tutagomes ,

Hello, in conversation with one of the organizers, our date and event will not impact the public.

Where the public is at different ends of the country, which will not cause conflict between the public or sponsors.

2024-04-29 15:39 UTC, phrawzty requested changes

2024-04-29 15:39 UTC, phrawzty commented on data/events/2024/fortaleza/main.yml
> +  - name: program
Strongly suggest disabling this link until you actually have a programme to share.
```suggestion
  #- name: program
```

2024-04-29 15:39 UTC, phrawzty commented on data/events/2024/fortaleza/main.yml
> +  - name: speakers
Strongly suggest disabling this link until you actually have speakers to share.
```suggestion
  - name: speakers
```

2024-04-29 17:56 UTC, ana-aguilar7 commented on data/events/2024/fortaleza/main.yml
> +  - name: speakers
@phrawzty done.
Can you check, please?

2024-04-29 19:42 UTC, merged