A note about leveraging JJ's ignite karaoke app
devopsdays/devopsdays-web pull request #14057
Opened 2024-05-09 18:09 UTC by jjasghar

Instead of brining it into devopsdays github, here's a link to the app to make organizers life easier.

2024-05-09 18:21 UTC, adrianmoisey commented on content/page/organizing.md
> +If you are looking for a way to fill in for more ignites (pad the schedule) or have some fun with volunteers "Ignite Karaoke" is a great way to engage with your audiance. The idea is just one minute
```suggestion
If you are looking for a way to fill in for more ignites (pad the schedule) or have some fun with volunteers "Ignite Karaoke" is a great way to engage with your audience. The idea is just one minute per volunteer, 4 slides 15 seconds each, with a title and some "funny" pictures. It works extremely well for some laughs and engagement, and people can enjoy it greatly. JJ Asghar has created a tool to help create these slides if you want to experiment with this new way expose more people to the ignite format in a fun manner. [GitHub repo](https://github.com/jjasghar/ignite_karaoke)
```

2024-05-09 22:52 UTC, jyee reviewed
LGTM.
Normally I hate PRs that modify more than what's being added/removed, but I appreciate that this is also removing trailing whitespace. :)

2024-05-09 22:52 UTC, jyee approved these changes

2024-05-10 01:57 UTC, jjasghar commented
squashed :)

2024-05-11 10:28 UTC, phrawzty requested changes
Agree with content, suggest mild rewording

2024-05-11 10:28 UTC, phrawzty commented on content/page/organizing.md
> +If you are looking for a way to fill in for more ignites (pad the schedule) or have some fun with volunteers "Ignite Karaoke" is a great way to engage with your audience. The idea is just one minute
```suggestion
If you're looking for a way to fill in for more ignites (i.e. pad the schedule), or just to have some fun, "Ignite Karaoke" is a great way to engage with your audience. The idea is straightforward: one minute per participant, four slides of 15 seconds each, where each slide has a title and a "funny" picture. It's great for some laughs and engagement—people really enjoy it! JJ Asghar maintains a tool to help create these slides if you want to experiment with this fun ignite format: [GitHub repo](https://github.com/jjasghar/ignite_karaoke)
```

2024-05-11 15:02 UTC, jjasghar commented
I'll have to squash it again.

2024-05-11 15:06 UTC, adrianmoisey commented
> I'll have to squash it again.

Don't worry about squashing, we normally squash and merge when merging into main.

2024-05-13 18:01 UTC, phrawzty approved these changes

2024-05-13 18:01 UTC, merged

2024-05-13 18:01 UTC, phrawzty commented
Thanks @jjasghar ! <3