[orgs] Add blogpost: Good, Better, Best.
devopsdays/devopsdays-web pull request #14111
Opened 2024-05-20 21:57 UTC by glasnt

Adds blog post for Good, Better, Best: How to budget for success

2024-05-21 14:28 UTC, jyee approved these changes
LGTM

2024-05-21 15:55 UTC, FloorD commented
LGTM (but you knew that already!)

2024-05-21 19:26 UTC, phrawzty requested changes
Overall fantastic and absolutely the sort of information we need to get out there.

2024-05-21 19:26 UTC, phrawzty commented on content/blog/good-better-best.md
> +individual city events. This isn’t changing. However, we would like to at least
May be worth clarifying _why_ we don't provide support. Remember: the public at large doesn't generally understand that we're community/distributed/zero-profit (and, frankly, not all organisers do either).

2024-05-21 19:26 UTC, phrawzty commented on content/blog/good-better-best.md
> +sponsors, and organizers. We hope this information will help us tailor guidance
This is a long sentence and it doesn't appear to terminate properly (?). Consider breaking it into two sentences and terminating the second.

2024-05-21 19:26 UTC, phrawzty commented on content/blog/good-better-best.md
> +we’re piloting a “post event survey”, where we’re asking events to share nuances
Do we know when / who / how / etc for the survey?

2024-05-21 19:26 UTC, phrawzty commented
As an item of discussion, I'm wondering if we could even make a spreadsheet to quickly plug numbers and dates in as a sort of example template. 💭

2024-05-27 05:37 UTC, glasnt commented on content/blog/good-better-best.md
> +individual city events. This isn’t changing. However, we would like to at least
Would love if you could put some words in here how you would phrase it (I'm not completely sure I understand it either, other than "always been that way")

2024-05-27 05:38 UTC, glasnt commented on content/blog/good-better-best.md
> +sponsors, and organizers. We hope this information will help us tailor guidance
```suggestion
about their event and how it ran. We know that most if not all devopsdays events
use the devopsdays.org website, so we can see how many sponsors and speakers
each event attracted, along with ticket pricing. But often the total number of
attendees and how the event actually felt on the ground, including attendees,
sponsors, and organizers. We hope this information will help us tailor guidance
```

2024-05-27 05:40 UTC, glasnt commented
> As an item of discussion, I'm wondering if we could even make a spreadsheet to quickly plug numbers and dates in as a sort of example template. 💭

I'm reluctant to provide a sample budget, as I don't want to disregard the financial complexities of different geographies (and, specifically, I don't want to accidentally create an untenable [mcdonalds budget](https://www.forbes.com/sites/laurashin/2013/07/18/why-mcdonalds-employee-budget-has-everyone-up-in-arms/?sh=57efe1d95216))

2024-05-27 09:05 UTC, phrawzty requested changes

2024-05-27 09:05 UTC, phrawzty commented on content/blog/good-better-best.md
> +individual city events. This isn’t changing. However, we would like to at least
It's "always been that way" because the global core doesn't really have a reliable source of independent income. 😅 We're effectively a charity-case that Chicago and Amsterdam hand some cash to in order to keep the lights on.

2024-05-27 09:05 UTC, phrawzty commented on content/blog/good-better-best.md
> +takes to happen.
Maybe just drop the preamble entirely? Also, this document is effectively about financial viability, so we should focus on that terminology (i.e. "success" means different things to different people).

```suggestion
This section is all about helping events—especially newer ones who may not have their own processes in place for this—to understand what would make their event financially viable, in terms of the number of attendees, the facilities offered, and the amount of sponsorship necessary to make these things happen. 
```

2024-05-31 11:49 UTC, phrawzty approved these changes

2024-06-06 06:19 UTC, glasnt commented on content/blog/good-better-best.md
> +Date = "2024-05-23T00:00:00-00:00"
```suggestion
Date = "2024-06-06T00:00:00-00:00"
```

2024-06-06 06:36 UTC, merged