[KER-2024] Add DevOpsDays Kerala 2024 Event
devopsdays/devopsdays-web pull request #14185
Opened 2024-06-11 08:46 UTC by libreminds

-  [x] Add DevOpsDays Kerala 2024 to the event

2024-06-11 19:57 UTC, phrawzty requested changes
It looks like you ran the `add_new_event.sh` script then opened the PR, which is absolutely the first step—now you need to fill in details about the event in general.

2024-06-11 19:57 UTC, phrawzty commented on data/events/2024/kerala/main.yml
> +enddate:  # The end date of your event. Leave blank if you don't have a venue reserved yet.
Given that you have a signed venue agreement with a firm date, you should put that date here.

2024-06-11 19:57 UTC, phrawzty commented on data/events/2024/kerala/main.yml
> +event_twitter: "devopskerala" # Change this to the twitter handle for your event such as devopsdayschi or devopsdaysmsp
This is not a valid [Xitter](https://x.com/devopskerala) account.

2024-06-11 19:57 UTC, phrawzty commented on content/events/2024-kerala/sponsor.md
> +Gold sponsors get a full table and Silver sponsors a shared table where they can interact with those interested to come visit during breaks. All attendees are welcome to propose any subject they want
This is the boilerplate sponsor text. Is it true / accurate for _your_ event?

2024-06-11 19:57 UTC, phrawzty commented on data/events/2024/kerala/main.yml
> +location_address: "" #Optional - use the street address of your venue. This will show up on the welcome page if set. Also used by the event_map shortcode!
Given that you have a signed venue agreement with a firm date, you should indicate that somewhere. Here is a reasonable spot.

2024-06-11 19:57 UTC, phrawzty commented on data/events/2024/kerala/main.yml
> +sponsor_levels:
These are the boilerplate sponsor levels. Are they true for _your_ event?

2024-06-12 03:56 UTC, libreminds commented on data/events/2024/kerala/main.yml
> +location_address: "" #Optional - use the street address of your venue. This will show up on the welcome page if set. Also used by the event_map shortcode!
Yes, added the same.

2024-06-12 03:56 UTC, libreminds commented on data/events/2024/kerala/main.yml
> +event_twitter: "devopskerala" # Change this to the twitter handle for your event such as devopsdayschi or devopsdaysmsp
corrected it.. thanks !

2024-06-12 03:56 UTC, libreminds commented on data/events/2024/kerala/main.yml
> +enddate:  # The end date of your event. Leave blank if you don't have a venue reserved yet.
Done. thanks!

2024-06-12 10:27 UTC, libreminds commented on content/events/2024-kerala/sponsor.md
> +Gold sponsors get a full table and Silver sponsors a shared table where they can interact with those interested to come visit during breaks. All attendees are welcome to propose any subject they want
I have corrected this to the initial plan we have in the refresh of this patch.. will add more details accordingly.

2024-06-12 10:28 UTC, libreminds commented on data/events/2024/kerala/main.yml
> +sponsor_levels:
Corrected this as per the plan so far. thanks !

2024-06-12 10:30 UTC, libreminds commented
> It looks like you ran the `add_new_event.sh` script then opened the PR, which is absolutely the first step—now you need to fill in details about the event in general.

Sure! added the requested details as a start for now. Will get these updated accordingly. Thanks!

2024-06-12 10:59 UTC, phrawzty approved these changes

2024-06-12 10:59 UTC, phrawzty commented on data/events/2024/kerala/main.yml
> +location_address: "Le Méridien Kochi, Nettoor, Maradu, Kochi, Ernakulam, Kerala 682304" #Optional - use the street address of your venue. This will show up on the welcome page if set. Also used by th
Wow, the photos for this location look lovely! :D

2024-06-12 10:59 UTC, phrawzty commented on data/events/2024/kerala/main.yml
> +enddate: 2024-09-28T20:00:00-08:00 # The end date of your event. Leave blank if you don't have a venue reserved yet.
Good job including the timestamp. 👍

2024-06-12 11:09 UTC, merged

2024-06-12 12:05 UTC, phrawzty commented on data/events/2024/kerala/main.yml
> +location_address: "Le Méridien Kochi, Nettoor, Maradu, Kochi, Ernakulam, Kerala 682304" #Optional - use the street address of your venue. This will show up on the welcome page if set. Also used by th
@libreminds Hah! I'd love to, but it's a bit of journey for me ;)

2024-06-12 13:29 UTC, sanujan commented on data/events/2024/kerala/main.yml
> +location_address: "Le Méridien Kochi, Nettoor, Maradu, Kochi, Ernakulam, Kerala 682304" #Optional - use the street address of your venue. This will show up on the welcome page if set. Also used by th
@phrawzty Thanks for the quick turnaround, Dan.