[SITE] add talk page
devopsdays/devopsdays-web pull request #14346
Opened 2024-07-15 09:07 UTC by toshywoshy

add a talk page based upon #12515

* all talks, workshops and ignites get displayed on a single page
* this page has the presentation title, the speakers, and when it is happening with the abstract
* all speakers are also displayed, with their picture and bio

2024-07-16 14:51 UTC, mattstratton commented
i think this is a good start! I would want to do a little bit more with the styling on this before merging it (the background color of each item is quite harsh, etc) but i think that with some visual style improvements this is a good one.

2024-07-17 15:13 UTC, camilla-m approved these changes
lgtm

2024-07-17 15:21 UTC, nimbinatus requested changes
Re styling, I'd like to see more padding in each container (probably 2em) to give more whitespace on the page. Color coding doesn't work well for accessibility reasons, so I'd try to find a different way to indicate type of talk. Italics also create problems for people who have reading issues (e.g., dyslexia). I can try to whip up some CSS for it, but I don't think reusing the styles from the program page will work since those really rely on having everything there without scrolling. If you can hang on for a few days, I'll see what I can mock up.

2024-07-17 16:38 UTC, toshywoshy commented
@nimbinatus Yes, this PR is not in a hurry, so if you can provide a mock up or any other additional feedback and information, that would be very helpful

I like the idea of adding  markers, for example some font-awesome icons, for talks, workshops and ignites, however I think we should have those consistent on the program, talk and speaker page.
I personally think having the same colors on all pages is good, this makes it easy to identify the type.
I do understand we might need different colors, but then we should change this on all pages involved and be consistent from now on.

I also think that once we do figure out the move to `hugo-extended` pipelines #13697 we can use SASS/LESS to better create multiple versions, like a high contrast version.

2024-07-29 14:44 UTC, toshywoshy commented
@nimbinatus Any news on the mockup or CSS updates?

2024-10-07 22:35 UTC, jerdog commented
> @nimbinatus Any news on the mockup or CSS updates?

I will try to take a look at mocking this up.

2024-10-09 16:15 UTC, nimbinatus commented
Sorry, folks, dayjob inhaled my time. No updates. I'll be picking this up mid next week unless someone who has some available cycles wants to.

2025-05-15 08:13 UTC, closed without merging