SANTIAGO-2025 first commit
devopsdays/devopsdays-web pull request #14340
Opened 2024-07-13 06:22 UTC by jorgevalenzuelad

SANTIAGO-2025 Santiago de Chile 2025 event web upload for devopsdays website. On July 12 we held the kickoff/onboarding meeting with Dan.

2024-07-15 14:29 UTC, nimbinatus commented
Hi! I've put the do-not-merge tag on this until we handle the email lists and all. One of us will review this PR after that thread has been completed. Thanks!

2024-07-16 19:09 UTC, jorgevalenzuelad commented
Thanks, I'm waiting

2024-07-17 15:26 UTC, nimbinatus commented
I'll be going through and reviewing later today :) Congrats on kickoff!

2024-07-17 16:51 UTC, kokedevops commented
Thanks Laura

2024-07-17 21:22 UTC, nimbinatus requested changes
Great start! Did you happen to use the `add-new-event.sh` script when setting up your event? In general, we really recommend using that script as there's a lot of small things that might break otherwise. I *think* I've caught everything, but we'll need to check once you've updated these.

Learn more at https://github.com/devopsdays/devopsdays-web/tree/main/utilities#events, which explains what the script is and how it's used.

2024-07-17 21:22 UTC, nimbinatus commented on data/sponsors/ciisa.yml
> +name: "ciisa"
At the moment, this sponsor was commented out in your datafile. Should it actually be listed? If so, you can leave this file in place and remove the `#` in front of the sponsor listing in your datafile.

2024-07-17 21:22 UTC, nimbinatus commented on static/_redirects
> +
This should be alphabetical, and would have been entered via the script. We really need you to use the add-event script instead of fixing everything manually.

Also, when I went to check the file, there already is a `/santiago/*` redirect entry and appears to be for the same city. That should be updated instead of adding a new one: https://github.com/devopsdays/devopsdays-web/blob/main/static/_redirects#L108

2024-07-17 21:22 UTC, nimbinatus commented on data/events/2025/santiago/main.yml
> +cfp_link: "" #if you have a custom link for submitting proposals, add it here. This will control the Propose menu item as well as the "Propose" button.
Note that, since you've translated the name of the "propose.md" file, you'll need to put your CFP link in here when you add the CFP dates to ensure the button in the banner does not get a 404 response. Unfortunately, the automated template for that assumes English, but remembering to fill this field in will override the automation.

2024-07-17 21:22 UTC, nimbinatus commented on data/events/2025/santiago/main.yml
> +registration_link: "" # If you have a custom registration link, enter it here. This will control the Registration menu item as well as the "Register" button.
Note that, since you've translated the name of the "register.md" file, you'll need to put your registration link in here when you add the registration dates to ensure the button in the banner does not get a 404 response. Unfortunately, the automated template for that assumes English, but remembering to fill this field in will override the automation.

2024-07-17 21:23 UTC, nimbinatus commented
If you get stuck on how to fix anything from my review, please reach out and ask :) Happy to help!

2024-07-17 22:35 UTC, kokedevops commented
> If you get stuck on how to fix anything from my review, please reach out and ask :) Happy to help!

   Thank you very much Laura for the help. It is very clear to me, I will modify what you tell me, I thank you and I will let you know if I have questions.

2024-07-17 23:25 UTC, closed without merging

2024-07-18 07:09 UTC, kokedevops commented
@nimbinatus Hello Laura, very good day to you.
I decided to start again to avoid errors, follow your instructions and the changes were sent in the pull https://github.com/devopsdays/devopsdays-web/pull/14366

2024-07-18 07:09 UTC, kokedevops commented on data/events/2025/santiago/main.yml
> +cfp_link: "" #if you have a custom link for submitting proposals, add it here. This will control the Propose menu item as well as the "Propose" button.
@nimbinatus Hello Laura, very good day to you.
I decided to start again to avoid errors, follow your instructions and the changes were sent in the pull https://github.com/devopsdays/devopsdays-web/pull/14366