[KER-2024]: update organizers, logo, sponsors..etc
devopsdays/devopsdays-web pull request #14382
Opened 2024-07-21 18:50 UTC by humblec

*Please read and take into consideration the following:*
- Title your pull request in this format: `[PLACE-YEAR] Brief description of the proposed change`. For example: `[CHI-2024] Add Bluth Company as a sponsor`
- Remove _this default text_ from the PR description, and replace it with a summary of the changes (e.g. 'Added 10 new speakers, Added 6 sponsors, Added emojis to CFP page').

*If you are adding or removing organizers*, send an email to info@devopsdays.org with the full names, email addresses, and organizations the added/removed persons represent. (The global team uses this information to maintain your mailing list as well as the Slack.)

Large files should go in https://github.com/devopsdays/devopsdays-assets/ . *If _this_ PR is related to an _assets_ PR*, please include a link to the latter.

Up to date guidelines for pull requests can be found in the [contributing guide](https://github.com/devopsdays/devopsdays-web/blob/main/CONTRIBUTING.md#guidelines).

If you are changing sponsor information, be sure you are [following the guidelines](https://github.com/devopsdays/devopsdays-web/blob/main/utilities/README.md#updating-a-sponsor-image-or-data).

2024-07-24 13:37 UTC, phrawzty requested changes

2024-07-24 13:37 UTC, phrawzty commented on content/events/2024-kerala/welcome.md
> +    <p>We are incredibly proud to be able to announce our program for our 2024 event which you can find <a href="/events/2024-kerala/program">here</a>. With a breadth of speakers from many background
Your programme has not, as far as I can tell, been announced. The `program` page is empty. Are you should about this wording?

Also, once you _are_ ready to announce, you can (and should) use built-ins for this. See https://github.com/devopsdays/devopsdays-web/pull/14382/files#diff-81f19987eef556de82f5927b0a05a7b9e0ca6115b4c61261adc2b3881a34fb09L71 (which you are deleting in this PR) for an example.

2024-07-24 13:37 UTC, phrawzty commented on content/events/2024-kerala/welcome.md
> +          <a class="btn btn-secondary btn-block" href="/events/2024-kerala/program"> <i class="fa fa-book fa-lg"></i>&nbsp;&nbsp;
Your programme has not, as far as I can tell, been announced. The `program` page is empty. Are you should about this button?

2024-07-24 13:37 UTC, phrawzty commented on data/events/2024/kerala/main.yml
> +    image: "/events/2024-kerala/organizers/dipu.jpeg"
We don't use paths here. Please see the [documentation](https://github.com/devopsdays/devopsdays-web/blob/main/themes/devopsdays-theme/reference.md#organizer-fields) for details, and literally any other `main.yml` that has organiser photos for examples.

2024-07-24 15:01 UTC, humblec commented on data/events/2024/kerala/main.yml
> +    image: "/events/2024-kerala/organizers/dipu.jpeg"
Sure, removed Program for now..

2024-07-24 17:29 UTC, humblec commented on data/events/2024/kerala/main.yml
>  cfp_date_end:  # close your call for proposals.
Sure.. thanks ! addressed the same.

2024-07-24 17:30 UTC, humblec commented on data/events/2024/kerala/main.yml
>  registration_date_end: # close registration. Leave blank if registration is not open yet. If you set "registration_date_start" you need a value here.
Done.

2024-07-24 17:30 UTC, humblec commented on data/events/2024/kerala/main.yml
>   # - name: registration
Awesome.. committed the changes as suggested

2024-07-24 17:45 UTC, humblec commented on static/events/2024-kerala/devopsdays-kerala-2024-sponsorship-brochure.pdf
Sure .. added it in assets repo and here is the PR https://github.com/devopsdays/devopsdays-assets/pull/212 @nimbinatus .. Thanks a lot!

2024-07-24 19:56 UTC, nimbinatus requested changes

2024-07-24 19:56 UTC, nimbinatus commented on data/events/2024/kerala/main.yml
> +     url: https://konfhub.com/devopsdays-kerala-2024
Whoops, I had an extra set of spaces. That's why the preview doesn't show anything. If you can accept these changes (or update and commit yourself), I can merge. (p.s., if you want to check this locally, are comfortable doing so, and you already have hugo installed, a `hugo serve` works just fine.)
```suggestion
  - name: register
    url: https://konfhub.com/devopsdays-kerala-2024
```

2024-07-25 03:48 UTC, libreminds commented
Thanks @nimbinatus . I have accepted the suggestion !! 👍

2024-07-25 03:49 UTC, libreminds commented on data/events/2024/kerala/main.yml
> +     url: https://konfhub.com/devopsdays-kerala-2024
Thanks.. I missed it too.. Have accomodated the changes

2024-07-25 12:12 UTC, libreminds commented
@nimbinatus looks we are good at rendering https://deploy-preview-14382--devopsdays-web.netlify.app/events/2024-kerala/welcome/

2024-07-25 15:16 UTC, phrawzty approved these changes

2024-07-25 15:16 UTC, merged

2024-07-25 15:19 UTC, humblec commented
Thanks a lot @phrawzty and @nimbinatus for quick review and approval 🎉