[CAC-2024] DevopsDays Cáceres - add speakers and sponsors
devopsdays/devopsdays-web pull request #14408
Opened 2024-07-30 11:50 UTC by neovasili

This PR adds latest confirmed sponsors and speakers.

2024-08-01 19:47 UTC, nimbinatus requested changes
Hi there! Can you resize a couple of the images?

2024-08-01 19:47 UTC, nimbinatus commented on static/events/2024-caceres/speakers/diego-duran.jpg
These files are a bit big. Can you resize to make the filesizes smaller? 600px by 600px usually does it; looking for the files to be under 1MB or else the site loads very slowly.

2024-08-01 19:47 UTC, nimbinatus commented on static/events/2024-caceres/speakers/rui-zhu.jpg
Resize, please :)

2024-08-02 10:05 UTC, neovasili commented on static/events/2024-caceres/speakers/diego-duran.jpg
resized!

2024-08-02 10:05 UTC, neovasili commented on static/events/2024-caceres/speakers/rui-zhu.jpg
resized!

2024-08-02 19:20 UTC, merged