[RIO-2024]Changed Logo Event and Remove Organizers
devopsdays/devopsdays-web pull request #14433
Opened 2024-08-05 13:27 UTC by mauriciopgomes

Changed Logo DevOps Days Rio
Remove Giovanni Martinss and Paloma Lataliza to Organization

2024-08-05 19:12 UTC, nimbinatus commented
Hi there! As this PR is changing the organizing team, you need to send that information to the info@ alias so global core can address the email lists and Slack per the [website directions](https://github.com/devopsdays/devopsdays-web/tree/main/utilities#local-organizers).

2024-08-06 07:54 UTC, phrawzty requested changes

2024-08-06 07:54 UTC, phrawzty commented on data/sponsors/grafana.yml
> +url: ""
```suggestion
url: "https://grafana.com"
```

2024-08-06 12:23 UTC, mauriciopgomes commented
> Hi there! As this PR is changing the organizing team, you need to send that information to the info@ alias so global core can address the email lists and Slack per the [website directions](https://github.com/devopsdays/devopsdays-web/tree/main/utilities#local-organizers).

sent a e-mail

2024-08-06 12:23 UTC, mauriciopgomes commented
> Hi there! As this PR is changing the organizing team, you need to send that information to the info@ alias so global core can address the email lists and Slack per the [website directions](https://github.com/devopsdays/devopsdays-web/tree/main/utilities#local-organizers).

sent e-mail

2024-08-07 15:07 UTC, merged