[ATL-2025] initial commit for Atlanta 2025
devopsdays/devopsdays-web pull request #14432
Opened 2024-08-05 02:37 UTC by ecology-chris

added dates, organizers, logos, and registration. All 2025 organizers are returning organizers.

2024-08-05 19:22 UTC, nimbinatus requested changes

2024-08-05 19:22 UTC, nimbinatus commented on data/events/2025/atlanta/main.yml
> +registration_date_start: 2025-04-29T00:00:00+02:00 # start accepting registration. Leave blank if registration is not open yet. This will make the "Register" button appear on your "Welcome" page.
Registration looks to be open; was this a date/time copy mistake?

2024-08-05 19:22 UTC, nimbinatus commented on data/events/2025/atlanta/main.yml
> +  - name: registration
[Non-blocking] might consider making this `register` instead of `registration` as it's an action.

2024-08-05 19:22 UTC, nimbinatus commented on static/events/2025-atlanta/organizers/brandy-griffin.jpg
Extra file?

2024-08-05 19:22 UTC, nimbinatus commented on static/events/2025-atlanta/organizers/savannah-champion.jpg
Extra file?

2024-08-05 23:45 UTC, ecology-chris commented on data/events/2025/atlanta/main.yml
> +registration_date_start: 2025-04-29T00:00:00+02:00 # start accepting registration. Leave blank if registration is not open yet. This will make the "Register" button appear on your "Welcome" page.
removed

2024-08-05 23:45 UTC, ecology-chris commented on data/events/2025/atlanta/main.yml
> +  - name: registration
updated to `register`

2024-08-05 23:45 UTC, ecology-chris commented on static/events/2025-atlanta/organizers/brandy-griffin.jpg
removed

2024-08-05 23:46 UTC, ecology-chris commented on static/events/2025-atlanta/organizers/savannah-champion.jpg
removed

2024-08-16 18:47 UTC, adrianmoisey commented on data/events/2025/atlanta/main.yml
> +enddate: 2025-04-30T00:00:00+02:00 # The end date of your event. Leave blank if you don't have a venue reserved yet.
Just want to point out that this ends at midnight on 2025-04-30.
If it's a 2 day event I suggest changing the time to the end of the day.
Also, the timezone isn't ET.

2024-08-16 18:47 UTC, adrianmoisey commented on data/events/2025/atlanta/main.yml
> +    level: gold
Remove the sample?

2024-08-20 22:02 UTC, ecology-chris commented on data/events/2025/atlanta/main.yml
> +enddate: 2025-04-30T00:00:00+02:00 # The end date of your event. Leave blank if you don't have a venue reserved yet.
times adjusted and in correct timezone

2024-08-20 22:02 UTC, ecology-chris commented on data/events/2025/atlanta/main.yml
> +    level: gold
removed sample sponsor.

2024-08-21 19:18 UTC, merged