[LA-2025] Initial commit for Los Angeles 2025
devopsdays/devopsdays-web pull request #14518
Opened 2024-08-29 20:22 UTC by omargohan

**Summary of changes:**

- Initial commit for Los Angeles 2025

**Tested:**

- Locally using Hugo

2024-09-02 04:16 UTC, brynak commented
Happy Labor Day Weekend, everyone! We're excited to get DevOpsDays Los Angeles 2025 launched. Please let us know how we can help. :)

2024-09-04 09:29 UTC, phrawzty requested changes

2024-09-04 09:29 UTC, phrawzty commented on data/events/2025/los-angeles/main.yml
> +team_members: # Name is the only required field for team members.
There are six entries on your team_members list, but seven addresses in your mail distribution list. These two lists must line up. Please either add the "missing" person to this list, or send an email to info@devopsdays.org with the name _and email address_ of the person to _remove_ from your distribution list.

2024-09-04 20:58 UTC, brynak commented on data/events/2025/los-angeles/main.yml
> +team_members: # Name is the only required field for team members.
thanks, @phrawzty . email sent to info@

2024-09-07 20:02 UTC, omargohan commented on data/events/2025/los-angeles/main.yml
> +team_members: # Name is the only required field for team members.
@phrawzty I have made some changes to the list. Thank you!

2024-09-08 14:07 UTC, phrawzty requested changes

2024-09-08 14:07 UTC, phrawzty commented on content/events/2025-los-angeles/propose.md
> +  <h2><a href="https://www.socallinuxexpo.org/scale/22x/cfp" style="font-size: 1.5em; padding: 5 10px;text-decoration: none; border-radius: 5px;">>>> Submit your proposal here <<<</a></h2>
The `<` and `>` symbols have a specific meaning in HTML, thus [page compilation will fail](https://github.com/devopsdays/devopsdays-web/actions/runs/10760428131/job/29838371448?pr=14518#step:7:13) if they're not treated properly. There are few ways to handle this situation; this is one suggestion.

```suggestion
  <h2><a href="https://www.socallinuxexpo.org/scale/22x/cfp" style="font-size: 1.5em; padding: 5 10px;text-decoration: none; border-radius: 5px;">&gt;&gt;&gt; Submit your proposal here &lt;&lt;&lt;</a></h2>
```

2024-09-08 14:07 UTC, phrawzty commented on data/events/2025/los-angeles/main.yml
> +team_members: # Name is the only required field for team members.
I confirm that the lists line up and have responded in email as well.

2024-09-08 14:31 UTC, adrianmoisey commented
Heads up that you may want to update the redirect here: https://github.com/devopsdays/devopsdays-web/blob/0085e7afb888527503d099766e579742b5be4d76/static/_redirects#L69

2024-09-08 20:18 UTC, omargohan commented on content/events/2025-los-angeles/propose.md
> +  <h2><a href="https://www.socallinuxexpo.org/scale/22x/cfp" style="font-size: 1.5em; padding: 5 10px;text-decoration: none; border-radius: 5px;">>>> Submit your proposal here <<<</a></h2>
Fixed, thank you for the suggestion.

2024-09-09 07:45 UTC, phrawzty approved these changes

2024-09-09 07:45 UTC, merged

2024-09-10 16:09 UTC, brynak commented
Thanks, Everybody!