[CAI-25] Creating Cairo 2025 event
devopsdays/devopsdays-web pull request #14630
Opened 2024-09-29 11:55 UTC by aameen79

Creating Cairo 2025 event, with logos and pages

2024-09-29 13:41 UTC, don-code commented
Can you also update `static/_redirects` to point at the 2025 event?

2024-09-29 14:48 UTC, aameen79 commented
I'm not sure if I know how to do so, I would appreciate your help for this :)

On Sep 29, 2024 4:40 PM, Don Luchini ***@***.***> wrote:

Can you also update static/_redirects to point at the 2025 event?

—
Reply to this email directly, view it on GitHub<https://github.com/devopsdays/devopsdays-web/pull/14630#issuecomment-2381362310>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AI72RY7YQZXKFL3SNQX6KZLZY77SHAVCNFSM6AAAAABPBURVASVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOBRGM3DEMZRGA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-09-29 16:22 UTC, jerdog commented
> I'm not sure if I know how to do so, I would appreciate your help for this :) 

@aameen79 you would edit [this line](https://github.com/aameen79/devopsdays-web/blob/76f39f37b92e1d911e5d8030108a3802ac407646/static/_redirects#L25) to point to the 2025 event, i.e. `/events/2025-cairo/:splat`

2024-09-29 16:44 UTC, aameen79 commented
Many thanks, done

On Sep 29, 2024 7:21 PM, Jeremy Meiss ***@***.***> wrote:

I'm not sure if I know how to do so, I would appreciate your help for this :)

@aameen79<https://github.com/aameen79> you would edit this line<https://github.com/aameen79/devopsdays-web/blob/76f39f37b92e1d911e5d8030108a3802ac407646/static/_redirects#L25> to point to the 2025 event, i.e. /events/2025-cairo/:splat

—
Reply to this email directly, view it on GitHub<https://github.com/devopsdays/devopsdays-web/pull/14630#issuecomment-2381415873>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AI72RY3ZT2UNDJ7273FQO6TZZASN7AVCNFSM6AAAAABPBURVASVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOBRGQYTKOBXGM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-30 10:15 UTC, aameen79 commented
Kind reminder to book the event :)

2024-09-30 10:16 UTC, aameen79 commented
Also email sent to info yesterday

2024-09-30 16:51 UTC, nimbinatus requested changes
If you have any trouble with making the logo-square.jpg file actually square, please let us know!

Otherwise, all global core updates have been made; once this file is squared off, then this can be merged.

2024-09-30 16:51 UTC, nimbinatus commented on static/events/2025-cairo/logo-square.jpg
Hi there! One last change before I can merge this as core. Can you make this image file actually square, please? You can add white space around it to make it square; no need to make a new logo or anything. It needs to be square to ensure the main page on the website loads properly.

The other logo file can be left as is.

2024-09-30 16:53 UTC, nimbinatus commented on static/events/2025-cairo/logo-square.jpg
(For reference, this patch was manually done for the 2024 file; it can be copied if that's easier: https://github.com/devopsdays/devopsdays-web/pull/14462/files#diff-fb239e5bde62db7d6567ee309d37c8813932609cb347332c5041749b19b3cc40)

2024-10-01 14:29 UTC, aameen79 commented
Fixed, thanks

From: Laura Santamaria ***@***.***>
Sent: Monday, September 30, 2024 7:54 PM
To: devopsdays/devopsdays-web ***@***.***>
Cc: Ahmed Ameen ***@***.***>; Mention ***@***.***>
Subject: Re: [devopsdays/devopsdays-web] [CAI-25] Creating Cairo 2025 event (PR #14630)


@nimbinatus commented on this pull request.

________________________________

On static/events/2025-cairo/logo-square.jpg<https://github.com/devopsdays/devopsdays-web/pull/14630#discussion_r1781461926>:

(For reference, this patch was manually done for the 2024 file; it can be copied if that's easier: https://github.com/devopsdays/devopsdays-web/pull/14462/files#diff-fb239e5bde62db7d6567ee309d37c8813932609cb347332c5041749b19b3cc40)

—
Reply to this email directly, view it on GitHub<https://github.com/devopsdays/devopsdays-web/pull/14630#discussion_r1781461926>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AI72RY6QYJ3Q6FLRFRSPHW3ZZF6YZAVCNFSM6AAAAABPBURVASVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMZYGEYDKMBXGU>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2024-10-01 14:45 UTC, nimbinatus approved these changes
All changes for global core are completed. LGTM

2024-10-01 14:45 UTC, merged