[Raleigh-2025] Added an Organizer and two Community Sponsors
devopsdays/devopsdays-web pull request #14697
Opened 2024-10-21 14:42 UTC by jrn00

Added Shawn Taylor as an Organizer
     - Added picture
    - Added info in RDU main.yml
    
Added KubeEvents and KubeCareers under Community in main.yml

2024-10-21 16:38 UTC, toshywoshy requested changes

2024-10-21 16:38 UTC, toshywoshy commented on static/events/2025-raleigh/organizers/shawn-taylor.jpg
Please add picture to the assets folder
`assets/events/2025-raleigh/organizers/`

2024-10-21 16:39 UTC, toshywoshy commented
Adding a new organizer requires @core to approve mailinglist changes and the new organizer

2024-10-21 16:52 UTC, jrn00 commented on static/events/2025-raleigh/organizers/shawn-taylor.jpg
I've added his picture to static/events/2025-raleigh/organizers

That's where the rest of our portraits reside. 

Was there a change?

2024-10-22 14:27 UTC, jrn00 commented on static/events/2025-raleigh/organizers/shawn-taylor.jpg
Also, email sent to Core

2024-10-22 14:29 UTC, nimbinatus commented on static/events/2025-raleigh/organizers/shawn-taylor.jpg
Hey Jeremy! I'm going through and doing the organizer update now. Yes, images are being moved to the assets directory (https://github.com/devopsdays/devopsdays-web/pull/14341). At the moment, both *should* work, iirc, and should not be a breaking change, but we're working on getting folks to get used to the new workflow.

That being said, there's something up with the preview. No events are showing, and I can't get to the logs to find out what's up. I'll pull it down here in a moment and figure out what's going on.

2024-10-22 14:40 UTC, nimbinatus submitted a review, later dismissed
Found the break, and a couple other things. I'll reply to the email with the distro update confirmation in a minute.

2024-10-22 14:44 UTC, nimbinatus commented
Core updates complete; once you've gotten this PR patched, anyone can review and merge (fyi to @devopsdays/content-reviewers )

2024-10-22 20:29 UTC, jrn00 commented on static/events/2025-raleigh/organizers/shawn-taylor.jpg
Thanks Laura!

I made those suggested Changes. 

I can move our pics over to the assets directory here soon.

2024-10-22 22:51 UTC, toshywoshy approved these changes

2024-10-22 22:59 UTC, toshywoshy approved these changes

2024-10-22 23:01 UTC, merged