[LA-2025] Adding prospectus info
devopsdays/devopsdays-web pull request #14706
Opened 2024-10-26 15:13 UTC by omargohan

**Summary of changes:**

- Added the sponsor prospectus PDF
- Added images to the sponsor's page
- Added link to the welcome page

**Tested:**

- Locally using hugo

2024-10-26 15:43 UTC, toshywoshy requested changes

2024-10-26 15:43 UTC, toshywoshy commented on static/events/2025-los-angeles/devopsdayla2025_sponsor.pdf
This should be in the assets repo `https://github.com/devopsdays/devopsdays-assets/`
While it does not hit the 5M limit, these are files we should keep external to this repo

2024-10-26 20:50 UTC, omargohan commented on static/events/2025-los-angeles/devopsdayla2025_sponsor.pdf
Done https://github.com/devopsdays/devopsdays-assets/pull/217

2024-10-27 08:55 UTC, toshywoshy approved these changes

2024-10-27 08:55 UTC, merged