Add Sustainability Donation to Organisers guide
devopsdays/devopsdays-web pull request #14719
Opened 2024-11-08 03:00 UTC by glasnt

Majority approved by core organisers. 

**Executive summary**

Starting 1 January 2025, a modest, localised event fee will be introduced. This will be used solely to ensure a sustainable model to pay for the underlying infrastructure that powers the DevOpsDays global community. Both the global organisation and local events themselves will continue to be volunteer-run, and none of these funds will be used to remunerate volunteers at any level.

---

This PR proposes adding this to the organiser guide. After merging, blog post to come.

2024-11-08 03:05 UTC, glasnt commented on content/page/organizing.md
> +#### Sustainability Donation FAQs
Having H3 headers makes the TOC look strange, reduce that. 

```suggestion
### Sustainability Donation FAQs
```

2024-11-08 09:43 UTC, phrawzty requested changes
Minor changes since this is long term doc and not a punctual email.

2024-11-08 09:43 UTC, phrawzty commented on content/page/organizing.md
> +The management and operations of the DevOpsDays infrastructure has always been, and will continue to be, run on a volunteer basis. The services that provide this infrastructure, however, are not free
```suggestion
The management and operations of the DevOpsDays infrastructure has always been, and will continue to be, run on a volunteer basis. The services that provide this infrastructure, however, are not free. While we have benefitted from punctual donations and free tiers of services over the years, the reality is that this model is not sustainable. In order to promote a sustainable funding model, and to ensure the continuity of the DevOpsDays global community, as of 1 January 2025, we are introducing a modest event fee: each time you run an event (generally once per year), you donate the equivalent of at least **one full price attendee ticket to your event** to the global DevOpsDays organisation (though you may choose to donate more, if you want). 
```

2024-11-08 09:43 UTC, phrawzty commented on content/page/organizing.md
> +We actively encourage feedback on this from the local event organisers—especially from locations outside of our initial two regions. We further understand that local events may have no familiarity wi
```suggestion
```

2024-11-08 09:43 UTC, phrawzty commented on content/page/organizing.md
> +Today, we have the means and logistics in place to handle financial transactions in USD in the United States of America via ConferenceOps, and in official European currencies within the European Unio
```suggestion
Currently, we have the means and logistics in place to handle financial transactions in USD in the United States of America via ConferenceOps, and in official European currencies within the European Union via the Stichting DevOps Foundation. For this reason, we will be asking DevOpsDays events in those regions to participate in this sustainability programme from 1 January 2025. Events in other regions will be onboarded as we build out our capacity to manage them. 
```

2024-11-11 11:00 UTC, phrawzty requested changes
Oops, missed this one in the first pass.

2024-11-11 11:00 UTC, phrawzty commented on content/page/organizing.md
> +* **T-5 months before Event:** Pay sustainability donation
```suggestion
* **T-5 months before Event:** Contribute "sustainability donation"
```

2024-11-11 11:00 UTC, phrawzty approved these changes

2024-11-11 13:01 UTC, merged