[Natal - 2024] Add new organizer and config link for registration
devopsdays/devopsdays-web pull request #14718
Opened 2024-11-07 19:47 UTC by luancarlos021

- Insert new organizers
- Insert link for registration

2024-11-08 08:54 UTC, toshywoshy requested changes

2024-11-08 08:54 UTC, toshywoshy commented on data/events/2024/natal/main.yml
> +
this requires a mail to info@

2024-11-08 12:51 UTC, luancarlos021 commented on data/events/2024/natal/main.yml
> +
@toshywoshy

Email already sent to [info@devopsdays.org](mailto:info@devopsdays.org)

2024-11-13 20:20 UTC, nimbinatus commented on data/events/2024/natal/main.yml
> +
Looks like this was taken care of; apologies for the delay in merging.

2024-11-13 20:20 UTC, nimbinatus approved these changes

2024-11-13 20:22 UTC, merged