[SLC-2025] Open CFP and add dates
devopsdays/devopsdays-web pull request #14737
Opened 2024-11-21 15:59 UTC by Clait

- Open CFP/dates
- Add conference dates
- Add propose page nav element
- Update logo 
- Remove Alex as an organizer for 2025

2024-11-22 11:14 UTC, toshywoshy requested changes

2024-11-22 11:14 UTC, toshywoshy commented on data/events/2025/salt-lake-city/main.yml
> +    #   linkedin: "https://www.linkedin.com/in/alex-c-bilimoria/"
This requires an email to info

2024-11-25 20:47 UTC, Clait commented on data/events/2025/salt-lake-city/main.yml
> +    #   linkedin: "https://www.linkedin.com/in/alex-c-bilimoria/"
> This requires an email to info

Sent!  Thanks.

2024-11-27 10:06 UTC, phrawzty commented
📧 received and processed

2024-11-27 10:21 UTC, phrawzty requested changes

2024-11-27 10:21 UTC, phrawzty commented on data/events/2025/salt-lake-city/main.yml
> +event_logo: "logo2.png"
There is no file named `logo2.png` in this pull request, nor anywhere in the current repository. Please either include this file, or adjust the filename to one that exists.

2024-11-27 22:09 UTC, toshywoshy approved these changes

2024-11-28 19:55 UTC, merged