[PRG-2025] Add sponsor levels
devopsdays/devopsdays-web pull request #14739
Opened 2024-11-21 22:32 UTC by EtssMM

- Adding sponsor levels
- Fixing default city redirect

2024-11-22 10:30 UTC, toshywoshy requested changes

2024-11-22 10:30 UTC, toshywoshy commented on content/events/2025-prague/sponsor.md
> +We greatly value sponsors for this open event.  If you are interested in sponsoring, please <a href="mailto:sponsors@devopsdays.cz?subject=Interested%20in%20Sponsoring%20DevOpsDays%20Prague%202025">s
Is there a reason you're not using the city email of DoD?

2024-11-25 22:01 UTC, EtssMM commented on content/events/2025-prague/sponsor.md
> +We greatly value sponsors for this open event.  If you are interested in sponsoring, please <a href="mailto:sponsors@devopsdays.cz?subject=Interested%20in%20Sponsoring%20DevOpsDays%20Prague%202025">s
There are 2 reasons:
- We want to be able to respond from the same domain
- We want to have flexibility who is receiving the emails as we might shuffle volunteers here and there and don't want to update the org list every time.

2024-11-26 02:28 UTC, toshywoshy commented on content/events/2025-prague/sponsor.md
> +We greatly value sponsors for this open event.  If you are interested in sponsoring, please <a href="mailto:sponsors@devopsdays.cz?subject=Interested%20in%20Sponsoring%20DevOpsDays%20Prague%202025">s
Can someone from core approve the off DoD email with the above reasons?
@mattstratton @nimbinatus @phrawzty

2024-11-28 20:57 UTC, EtssMM commented on content/events/2025-prague/sponsor.md
> +We greatly value sponsors for this open event.  If you are interested in sponsoring, please <a href="mailto:sponsors@devopsdays.cz?subject=Interested%20in%20Sponsoring%20DevOpsDays%20Prague%202025">s
We have used the same last time and I have seen it on other cities as well. Is there any reason why we should avoid it?

2024-11-28 22:00 UTC, toshywoshy commented on content/events/2025-prague/sponsor.md
> +We greatly value sponsors for this open event.  If you are interested in sponsoring, please <a href="mailto:sponsors@devopsdays.cz?subject=Interested%20in%20Sponsoring%20DevOpsDays%20Prague%202025">s
Well, there is always a trust issue, the webdomain is devopdays.org and using prague[at]devopsdays[dot]org seems better
However as you indicated correctly there is presidence on using another email address then the DoD mailing list.

2024-11-28 22:00 UTC, toshywoshy approved these changes

2024-11-28 22:00 UTC, merged