[SSA-2024] add program
devopsdays/devopsdays-web pull request #14745
Opened 2024-11-25 21:07 UTC by somatorio

Add initial program and speakers

2024-11-25 21:10 UTC, don-code requested changes
The images under `static/events` aren't needed - can you remove them? The ones under `assets/events` are the ones that should stay.

2024-11-25 21:57 UTC, toshywoshy requested changes

2024-11-25 21:57 UTC, toshywoshy commented on static/events/2024-salvador/speakers/rafael-levi-batista-costa.jpg
Please remove as already requested

2024-11-25 21:57 UTC, toshywoshy commented on static/events/2024-salvador/speakers/lucas-ribeiro-mata.jpeg
Please remove as already requested

2024-11-25 21:57 UTC, toshywoshy commented on static/events/2024-salvador/speakers/lara-xavier.jpeg
Please remove as already requested

2024-11-25 21:57 UTC, toshywoshy commented on static/events/2024-salvador/speakers/giovana-do-nascimento-pena.png
Please remove as already requested

2024-11-25 21:57 UTC, toshywoshy commented on static/events/2024-salvador/speakers/everton-mendonca-de-jesus.jpeg
Please remove as already requested

2024-11-25 21:57 UTC, toshywoshy commented on static/events/2024-salvador/speakers/eduardo-paim.png
Please remove as already requested

2024-11-25 21:57 UTC, toshywoshy commented on static/events/2024-salvador/speakers/clayton-cavaleiro.png
Please remove as already requested

2024-11-25 21:57 UTC, toshywoshy commented on static/events/2024-salvador/speakers/camilla-martins.jpeg
Please remove as already requested

2024-11-25 21:57 UTC, toshywoshy commented on content/events/2024-salvador/speakers/waldemar.md
> ++++
Speaker has no bio

2024-11-25 21:57 UTC, toshywoshy commented on content/events/2024-salvador/speakers/camila-viana.md
> ++++
Speaker has no bio

2024-11-25 21:57 UTC, toshywoshy commented on content/events/2024-salvador/program/camilla-martins.md
> +
Talk has no description

2024-11-25 21:57 UTC, toshywoshy commented on content/events/2024-salvador/program/clayton-cavaleiro.md
> +
Talk has no description

2024-11-25 21:57 UTC, toshywoshy commented on content/events/2024-salvador/program/eduardo-paim.md
> +
Talk has no description

2024-11-25 21:57 UTC, toshywoshy commented on content/events/2024-salvador/program/everton-mendonça-de-jesus.md
> +
Talk has no description

2024-11-25 21:57 UTC, toshywoshy commented on content/events/2024-salvador/program/lara-xavier.md
> +
Talk has no description

2024-11-25 21:57 UTC, toshywoshy commented on content/events/2024-salvador/program/lucas-ribeiro-mata.md
> +
Talk has no description

2024-11-25 21:57 UTC, toshywoshy commented on content/events/2024-salvador/program/rafael-levi-batista-costa.md
> +
Talk has no description

2024-11-26 22:17 UTC, don-code approved these changes

2024-11-26 22:19 UTC, don-code commented
I think this is fine. It looks like @toshywoshy will also need to reapprove before it can be merged.

2024-11-26 23:23 UTC, toshywoshy approved these changes

2024-11-26 23:24 UTC, merged