[BSB-2024] Remove organizers and add event schedule
devopsdays/devopsdays-web pull request #14740
Opened 2024-11-22 06:20 UTC by LORDBABUINO

### Removes Organizers

- Ana Sabino
- Matheus Araujo
- Rafael Santos
- Guaracy Carvajal
- Gustavo Santos

### Adds event schedule

2024-11-22 11:10 UTC, toshywoshy requested changes

2024-11-22 11:10 UTC, toshywoshy commented on data/events/2024/brasilia/main.yml
Requires email to info@

2024-11-22 11:10 UTC, toshywoshy commented on data/events/2024/brasilia/main.yml
> +  #   linkedin: "https://www.linkedin.com/in/gustavribeiro/"
Requires email to info@

2024-11-22 11:10 UTC, toshywoshy commented on content/events/2024-brasilia/program.md
> +</ul>
As you're setting the program yourself in html, you need to maintain it manually and consistent with the welcome page

2024-11-22 11:10 UTC, toshywoshy commented on content/events/2024-brasilia/welcome.md
> +  </div>
As you're setting the program yourself in html, you need to maintain it manually and consistent with the program page

2025-01-14 14:27 UTC, nimbinatus reviewed
The global core updates are complete; @toshywoshy, I'm not seeing the inconsistency on the two pages? Since this is past, though, we should merge it.

2025-01-14 14:27 UTC, nimbinatus commented on data/events/2024/brasilia/main.yml
Completed

2025-01-14 20:27 UTC, toshywoshy approved these changes

2025-01-15 09:31 UTC, toshywoshy approved these changes

2025-01-16 15:43 UTC, nimbinatus requested changes
Let's move theme changes to a different PR.

2025-01-16 15:43 UTC, nimbinatus commented on themes/devopsdays-theme/layouts/partials/program.html
> +{{- $.Scratch.Set "first" "true" -}}
Wait, why are you changing the theme here?

2025-02-02 03:08 UTC, LORDBABUINO commented on themes/devopsdays-theme/layouts/partials/program.html
> +{{- $.Scratch.Set "first" "true" -}}
I just made the program be loaded from a partial and the title load dynamically. Should I do it in another PR?

2025-02-02 06:01 UTC, mattstratton commented on themes/devopsdays-theme/layouts/partials/program.html
> +{{- $.Scratch.Set "first" "true" -}}
Yes, please separate content and code changes so that the code changes can be reviewed (and not block your content updates!)

2025-02-06 15:46 UTC, nimbinatus approved these changes

2025-02-06 15:46 UTC, merged

2025-02-06 15:46 UTC, nimbinatus commented
Thanks @LORDBABUINO! Looking forward to the code changes in a different PR :)