DSM-2025 - Des Moines 2025 Initial Setup
devopsdays/devopsdays-web pull request #14742
Opened 2024-11-22 17:46 UTC by jangolano

DSM-2025 - Des Moines 2025 Initial Setup
Initial Creation of 2025 Site
Added new organizers, sent an email about the new organizers

2024-11-22 17:51 UTC, toshywoshy requested changes

2024-11-22 17:51 UTC, toshywoshy commented on static/events/2025-des-moines/organizers/akrem-saed.jpg
Please move this image to the new asset folder`assets/events/2025-des-moines/organizers`

2024-11-22 17:51 UTC, toshywoshy commented on static/events/2025-des-moines/organizers/amy-lindberg.jpg
Please move this image to the new asset folder `assets/events/2025-des-moines/organizers`

2024-11-22 17:51 UTC, toshywoshy commented on static/events/2025-des-moines/organizers/bo-schatzberg.jpg
Please move this image to the new asset folder `assets/events/2025-des-moines/organizers`

2024-11-22 17:51 UTC, toshywoshy commented on static/events/2025-des-moines/organizers/crystal-newcomb.png
Please move this image to the new asset folder `assets/events/2025-des-moines/organizers`

2024-11-22 17:51 UTC, toshywoshy commented on static/events/2025-des-moines/organizers/willie-sandry.jpg
Please move this image to the new asset folder `assets/events/2025-des-moines/organizers`

2024-11-22 17:51 UTC, toshywoshy commented on static/events/2025-des-moines/organizers/tim-gifford.jpg
Please move this image to the new asset folder `assets/events/2025-des-moines/organizers`

2024-11-22 17:51 UTC, toshywoshy commented on static/events/2025-des-moines/organizers/ted-wallace.jpg
Please move this image to the new asset folder `assets/events/2025-des-moines/organizers`

2024-11-22 17:51 UTC, toshywoshy commented on static/events/2025-des-moines/organizers/paul-beers.jpg
Please move this image to the new asset folder `assets/events/2025-des-moines/organizers`

2024-11-22 17:51 UTC, toshywoshy commented on static/events/2025-des-moines/organizers/josh-angolano.jpg
Please move this image to the new asset folder `assets/events/2025-des-moines/organizers`

2024-11-22 17:51 UTC, toshywoshy commented on static/events/2025-des-moines/organizers/john-sonneville.jpg
Please move this image to the new asset folder `assets/events/2025-des-moines/organizers`

2024-11-22 17:51 UTC, toshywoshy commented on static/events/2025-des-moines/organizers/jodi-jones.jpg
Please move this image to the new asset folder `assets/events/2025-des-moines/organizers`

2024-11-22 17:51 UTC, toshywoshy commented on static/events/2025-des-moines/organizers/ethan-spoelstra.jpg
Please move this image to the new asset folder `assets/events/2025-des-moines/organizers`

2024-11-22 17:51 UTC, toshywoshy commented on static/events/2025-des-moines/organizers/joanna-springsteen.jpg
Please move this image to the new asset folder `assets/events/2025-des-moines/organizers`

2024-11-22 17:51 UTC, toshywoshy commented on data/events/2025/des-moines/main.yml
> +
Please send an email to info@

2024-11-22 18:05 UTC, jangolano commented on data/events/2025/des-moines/main.yml
> +
info email has been sent

2024-11-23 08:46 UTC, toshywoshy requested changes
Email info@ for updates

2024-11-23 15:06 UTC, adrianmoisey commented
> Email info@ for updates

Email received and actioned.
I haven't checked the rest of this PR, but that part is now unblocked

2024-11-24 02:05 UTC, toshywoshy approved these changes

2024-11-24 02:05 UTC, merged