[BAL-2025] setup baltimore 2025 site
devopsdays/devopsdays-web pull request #14743
Opened 2024-11-22 19:09 UTC by dsueltenfuss

Creating the site for the 2025 Baltimore even

2024-11-23 08:48 UTC, toshywoshy requested changes
- Please move to the new folder `assets/events/2025-baltimore/`
- Please email info@

2024-11-23 08:48 UTC, toshywoshy commented on static/events/2025-baltimore/bmore_skyline_inner_harbor.jpg
Please move to the new folder `assets/events/2025-baltimore/`

2024-11-23 08:48 UTC, toshywoshy commented on static/events/2025-baltimore/logo-bmore.png
Please move to the new folder `assets/events/2025-baltimore/`

2024-11-23 08:48 UTC, toshywoshy commented on static/events/2025-baltimore/organizers/charles-bushong.jpg
Please move to the new folder `assets/events/2025-baltimore/`

2024-11-23 08:48 UTC, toshywoshy commented on static/events/2025-baltimore/organizers/dave-sueltenfuss.jpg
Please move to the new folder `assets/events/2025-baltimore/`

2024-11-23 08:48 UTC, toshywoshy commented on static/events/2025-baltimore/organizers/jp-hechter.png
Please move to the new folder `assets/events/2025-baltimore/`

2024-11-23 08:48 UTC, toshywoshy commented on static/events/2025-baltimore/organizers/judy-johnson.jpg
Please move to the new folder `assets/events/2025-baltimore/`

2024-11-23 08:48 UTC, toshywoshy commented on static/events/2025-baltimore/pava-center.jpg
Please move to the new folder `assets/events/2025-baltimore/`

2024-11-26 17:10 UTC, phrawzty commented
organiser email received and processed

2024-11-26 17:13 UTC, phrawzty approved these changes

2024-11-26 17:19 UTC, toshywoshy approved these changes

2024-11-26 17:20 UTC, merged