[AMS-2025] Add new organizers
devopsdays/devopsdays-web pull request #14752
Opened 2024-11-30 17:54 UTC by FloorD

Adding several new organizers for Amsterdam 2025

*If you are adding or removing organizers*, send an email to info@devopsdays.org with the full names, email addresses, and organizations the added/removed persons represent. (The global team uses this information to maintain your mailing list as well as the Slack.)
I will do this shortly, but can also edit the ML myself.

2024-11-30 20:49 UTC, issyl0 reviewed
Yes, ordinarily I'd approve, but since I'm one of them I won't approve directly. Also it requires an email to Core to add to the mailing lists, which I'm not privy to.

2024-12-01 10:25 UTC, toshywoshy requested changes
Please move the images to the assets folder
And you need to mail info@

2024-12-01 10:25 UTC, toshywoshy commented on static/events/2025-amsterdam/organizers/bram.png
Please move to `assets/events/2025-amsterdam/organizers/`

2024-12-01 10:25 UTC, toshywoshy commented on static/events/2025-amsterdam/organizers/issy.jpeg
Please move to `assets/events/2025-amsterdam/organizers/`

2024-12-01 10:25 UTC, toshywoshy commented on static/events/2025-amsterdam/organizers/joep.png
Please move to `assets/events/2025-amsterdam/organizers/`

2024-12-01 10:25 UTC, toshywoshy commented on static/events/2025-amsterdam/organizers/nati.jpg
Please move to `assets/events/2025-amsterdam/organizers/`

2024-12-01 10:25 UTC, toshywoshy commented on static/events/2025-amsterdam/organizers/stephan.png
Please move to `assets/events/2025-amsterdam/organizers/`

2024-12-02 15:21 UTC, FloorD commented
> Please move the images to the assets folder And you need to mail info@

I already sent that email, and updated the group. Will move the pictures next.

2024-12-02 16:46 UTC, jerdog commented
@FloorD I went ahead and merged the changes from main into the branch to kick-off the final checks

2024-12-02 17:14 UTC, toshywoshy approved these changes

2024-12-02 17:14 UTC, merged