[PRG-2025] Open cfp and sponsor improvements
devopsdays/devopsdays-web pull request #14759
Opened 2024-12-03 20:36 UTC by EtssMM

Open CFP
Improve sponsor page  - depends on https://github.com/devopsdays/devopsdays-assets/pull/219

2024-12-03 23:38 UTC, toshywoshy approved these changes

2024-12-03 23:39 UTC, toshywoshy commented
LGTM

2024-12-05 02:12 UTC, don-code commented
Should the two dates be in 2025? They're in the past (2024), so some of the links on the site intentionally won't show your CFP as open.

2024-12-06 01:33 UTC, toshywoshy requested changes

2024-12-06 01:33 UTC, toshywoshy commented on data/events/2025/prague/main.yml
>  cfp_date_announce:  # inform proposers of status
As @don-code mentioned, these should be respectivaly
`2024-12-01T00:00:00+00:00`
and
`2025-01-03T00:00:00+00:00`

2024-12-06 19:58 UTC, EtssMM commented on data/events/2025/prague/main.yml
>  cfp_date_announce:  # inform proposers of status
stupid me, thanks, should be fixed

2024-12-06 22:34 UTC, toshywoshy approved these changes

2024-12-06 22:34 UTC, merged