[LIMA-2025] Create new event
devopsdays/devopsdays-web pull request #14777
Opened 2024-12-23 01:08 UTC by edanpiro

This pull request includes several new pages and content updates for the DevOpsDays Lima 2025 event. The changes span multiple files, focusing on adding detailed information about the event, including the code of conduct, contact details, location, proposal submission guidelines, registration, sponsorship, and a welcome message.

Key changes:

### Event Information Updates:
* [`content/events/2025-lima/conduct.md`](diffhunk://#diff-42f417651769839c9b6ea785e028c24f6c0ad22ace5436f94d34ae4a82101deaR1-R28): Added the English version of the code of conduct for DevOpsDays Lima 2025.
* [`content/events/2025-lima/conduct-fr.md`](diffhunk://#diff-b94460d2ed8b124a30b3de935699a0b565866ac78fc142f6fc9b5cf35b62e714R1-R37): Added the French version of the code of conduct for DevOpsDays Lima 2025.
* [`content/events/2025-lima/conduct-pt-br.md`](diffhunk://#diff-a43cd551fece3ff48609325da34134ac4e4092ca7c2ed272869f2369d3a6a004R1-R28): Added the Portuguese version of the code of conduct for DevOpsDays Lima 2025.

### Contact and Location Information:
* [`content/events/2025-lima/contact.md`](diffhunk://#diff-627c3108e4af7bf8b9f89556bfbd045afcae5345a8faf6e042708bf553232454R1-R14): Added a contact page with email and organizer information for DevOpsDays Lima 2025.
* [`content/events/2025-lima/location.md`](diffhunk://#diff-a4a849dfee0b8cd6081b86467f1e2369b615d4e8c7089a1d8a9138c9078d9de5R1-R17): Added a location page with placeholder text for venue details for DevOpsDays Lima 2025.

### Proposal and Registration Guidelines:
* [`content/events/2025-lima/propose.md`](diffhunk://#diff-f9c2306b5dbaa5c6dbc36d6eac6a7d77bc256f62f8ba23e88fe597ace0011347R1-R35): Added guidelines for proposing talks, including submission instructions and selection criteria.
* [`content/events/2025-lima/registration.md`](diffhunk://#diff-d0163a8268914ae2a416b77e61911bec42ce95e3eef574981588248fe8363750R1-R11): Added a registration page with placeholder text for embedding registration details.

### Sponsorship and Welcome Message:
* [`content/events/2025-lima/sponsor.md`](diffhunk://#diff-710c35366b33a13cb971145c75d9a34bf74a0880aafcc77ca6ca3880ee15ba18R1-R66): Added sponsorship information, including benefits and contact details for potential sponsors.
* [`content/events/2025-lima/welcome.md`](diffhunk://#diff-0c7fd732d1fad538efcc72b3a02c6acfe2e01ff7a0b0ecb8f882ce70001b5523R1-R51): Added a welcome message with event details and organizer contact information.

2024-12-23 11:06 UTC, toshywoshy requested changes

2024-12-23 11:06 UTC, toshywoshy commented on static/events/2025-lima/logo-square.jpg
These are not needed anymore.

2024-12-23 11:06 UTC, toshywoshy commented on static/events/2025-lima/logo-square.png
These are not needed anymore.

2024-12-23 11:06 UTC, toshywoshy commented on static/events/2025-lima/sharing.png
These are not needed anymore.

2024-12-23 11:06 UTC, toshywoshy commented on static/events/2025-lima/logo.png
These are not needed anymore.

2024-12-23 11:06 UTC, toshywoshy commented on assets/events/2025-lima/logo-square.jpg
This is not needed, as you have a png version already

2024-12-23 11:06 UTC, toshywoshy commented on assets/events/2025-lima/logo-square copy.png
This is not needed, as you have a png version already.
The name is also wrong, but as this serves no purpose, please remove it

2024-12-23 11:06 UTC, toshywoshy commented on data/events/2025/lima/main.yml
> +
There is no start or end date entered yet

2024-12-23 13:40 UTC, edanpiro commented on data/events/2025/lima/main.yml
> +
These dates will be defined in the coming weeks. We hope this is not a prerequisite for approving the PR and granting us access to the DevOpsDays Slack channel

2024-12-23 15:14 UTC, toshywoshy commented on data/events/2025/lima/main.yml
> +
So without a `startdate` or `enddate`, this event will not show on the main page, so I would say this is needed, even if the dates are tentative, but then mention it.
As for the Slack channel, there should be no problem in asking that, it requires an email to info@

2024-12-24 16:07 UTC, edanpiro commented on data/events/2025/lima/main.yml
> +
date added

2025-01-05 04:58 UTC, edanpiro commented on data/events/2025/lima/main.yml
> +
> So without a `startdate` or `enddate`, this event will not show on the main page, so I would say this is needed, even if the dates are tentative, but then mention it. As for the Slack channel, there should be no problem in asking that, it requires an email to info@

date added

2025-01-05 12:30 UTC, toshywoshy approved these changes

2025-01-05 12:39 UTC, toshywoshy requested changes

2025-01-05 12:39 UTC, toshywoshy commented on assets/events/2025-lima/organizers/Doris_Manrique.jpg
The file name must be in lower case, please chang to all lower case

2025-01-05 12:39 UTC, toshywoshy commented on assets/events/2025-lima/organizers/Edgard_Pimentel.jpg
The file name must be in lower case, please chang to all lower case

2025-01-05 12:39 UTC, toshywoshy commented on assets/events/2025-lima/organizers/Lenard_Vega.jpg
The file name must be in lower case, please chang to all lower case

2025-01-05 12:39 UTC, toshywoshy commented on assets/events/2025-lima/organizers/Mario_Inga.jpg
The file name must be in lower case, please chang to all lower case

2025-01-07 19:44 UTC, edanpiro commented on assets/events/2025-lima/organizers/Doris_Manrique.jpg
updated name

2025-01-07 19:44 UTC, edanpiro commented on assets/events/2025-lima/organizers/Lenard_Vega.jpg
updated name

2025-01-07 20:53 UTC, toshywoshy approved these changes

2025-01-08 17:35 UTC, merged